/* ===========================================================
   Network+ N10-009 — Dedicated Practice Exam Bank
   Fresh, scenario-style questions used ONLY by the full practice exam.
   No overlap with the per-video quizzes or section exams.
   Keyed by domain (1-5). Each: { q, options[], answer (index), explain }
   =========================================================== */
const EXAM_BANK = {};

/* ---------------- Domain 1: Networking Concepts ---------------- */
Object.assign(EXAM_BANK, { "1": [
  {q:"A technician needs to encapsulate data with source and destination MAC addresses. At which OSI layer does this occur?",
   options:["Layer 2 – Data Link","Layer 3 – Network","Layer 4 – Transport","Layer 7 – Application"], answer:0,
   explain:"MAC addressing and framing happen at Layer 2 (Data Link)."},
  {q:"An application requires guaranteed, in-order delivery of a large file. Which transport protocol is appropriate?",
   options:["TCP","UDP","ICMP","ARP"], answer:0,
   explain:"TCP provides reliable, ordered, connection-oriented delivery."},
  {q:"A VoIP call favors low latency over guaranteed delivery. Which transport protocol is typically used?",
   options:["UDP","TCP","HTTP","FTP"], answer:0,
   explain:"UDP's low overhead suits real-time traffic like VoIP where speed matters more than retransmission."},
  {q:"Which port must be open for a client to reach a secure web server?",
   options:["443","25","110","69"], answer:0,
   explain:"HTTPS uses TCP 443."},
  {q:"A help desk tech uses port 3389 to remotely control a Windows desktop. Which protocol is this?",
   options:["RDP","SSH","Telnet","SMB"], answer:0,
   explain:"RDP (Remote Desktop Protocol) uses TCP 3389."},
  {q:"A device is assigned 169.254.10.5. What most likely happened?",
   options:["It could not reach a DHCP server (APIPA)","It received a public IP","It is using IPv6","It is on the loopback"], answer:0,
   explain:"169.254.x.x is APIPA, self-assigned when DHCP is unavailable."},
  {q:"How many usable host addresses are available in a /29 subnet?",
   options:["6","8","14","2"], answer:0,
   explain:"/29 = 8 addresses − 2 (network + broadcast) = 6 usable hosts."},
  {q:"A company needs to divide 192.168.1.0/24 into subnets of 50 hosts each. Which mask fits best?",
   options:["/26 (255.255.255.192)","/28 (255.255.255.240)","/24 (255.255.255.0)","/30 (255.255.255.252)"], answer:0,
   explain:"/26 gives 62 usable hosts per subnet — the smallest that fits 50 hosts."},
  {q:"Which cable category is required to reliably run 10GBASE-T for a full 100 meters?",
   options:["Cat 6a","Cat 5","Cat 5e","Cat 3"], answer:0,
   explain:"Cat 6a supports 10 Gbps to 100 m; Cat 6 only reaches ~55 m at 10 Gbps."},
  {q:"A run between two buildings 800 meters apart needs Ethernet. Which media is appropriate?",
   options:["Single-mode fiber","Cat 6 copper","Coaxial","Cat 5e copper"], answer:0,
   explain:"Copper is limited to 100 m; single-mode fiber handles long-distance runs."},
  {q:"Which connector would you expect on a fiber patch cable?",
   options:["LC","RJ45","RJ11","BNC"], answer:0,
   explain:"LC (and SC/ST) are fiber connectors; RJ45/RJ11 are copper."},
  {q:"A wireless design must minimize interference from microwaves and Bluetooth. Which band should be preferred where possible?",
   options:["5 GHz","2.4 GHz","900 MHz","AM band"], answer:0,
   explain:"5 GHz avoids much of the congestion/interference common in the 2.4 GHz band."},
  {q:"A technician sees three APs set to channels 1, 6, and 11 in 2.4 GHz. Why?",
   options:["These channels do not overlap","They are the fastest channels","They use less power","They are required for WPA3"], answer:0,
   explain:"1, 6, and 11 are the non-overlapping 2.4 GHz channels, reducing interference."},
  {q:"Which cloud connectivity method avoids the public internet for predictable performance?",
   options:["A dedicated direct/private connection","A standard VPN over broadband","Dial-up","Public DNS"], answer:0,
   explain:"A direct/private connection to the provider bypasses the public internet."},
  {q:"An organization wants an isolated, logically separated network within its cloud provider. This is a:",
   options:["VPC","VLAN trunk","CDN","MDF"], answer:0,
   explain:"A Virtual Private Cloud (VPC) provides an isolated virtual network in the cloud."},
  {q:"A retailer offloads static images to servers near users worldwide to speed load times. This uses a:",
   options:["CDN","VPN","DMZ","PDU"], answer:0,
   explain:"A Content Delivery Network caches content geographically closer to users."},
  {q:"An IPv6 address beginning with FE80:: is a:",
   options:["Link-local address","Global unicast address","Multicast address","Loopback"], answer:0,
   explain:"FE80::/10 addresses are link-local, valid only on the local segment."},
  {q:"Which technology extends Layer 2 segments across a Layer 3 network in large data centers?",
   options:["VXLAN","STP","NAT","PoE"], answer:0,
   explain:"VXLAN tunnels Layer 2 over Layer 3 and scales to ~16 million segments."},
  {q:"A network team manages device configuration using version-controlled templates that deploy automatically. This is:",
   options:["Infrastructure as Code","Manual configuration","Static routing","Port mirroring"], answer:0,
   explain:"IaC defines and deploys infrastructure through code for consistency and automation."},
  {q:"Which describes a full mesh topology?",
   options:["Every node connects directly to every other node","All nodes share one bus","Nodes form a single ring","All nodes connect to one hub"], answer:0,
   explain:"Full mesh links every node to every other for maximum redundancy."},
  {q:"In a data center, server-to-server traffic within the facility is called:",
   options:["East-west traffic","North-south traffic","Broadcast traffic","Loopback traffic"], answer:0,
   explain:"East-west is internal server-to-server; north-south is client-to-server in/out of the DC."},
  {q:"Which protocol dynamically assigns IP configuration to clients?",
   options:["DHCP","DNS","SNMP","NTP"], answer:0,
   explain:"DHCP leases IP addresses and related configuration to clients."},
  {q:"What is the decimal value of the subnet mask /27?",
   options:["255.255.255.224","255.255.255.192","255.255.255.240","255.255.255.128"], answer:0,
   explain:"/27 = 27 network bits = 255.255.255.224."},
  {q:"Which statement about a hub is TRUE?",
   options:["It repeats incoming signals out all ports (Layer 1)","It forwards by MAC address","It routes between subnets","It performs NAT"], answer:0,
   explain:"A hub is a Layer 1 repeater that floods all ports; it makes no forwarding decisions."},
  {q:"A technician must connect two switches and carry multiple VLANs over one link. The link should be configured as a:",
   options:["Trunk port","Access port","Loopback","Console port"], answer:0,
   explain:"A trunk port carries multiple VLANs (tagged with 802.1Q) between switches."},
  {q:"Which service resolves www.example.com to an IP address?",
   options:["DNS","DHCP","SNMP","ARP"], answer:0,
   explain:"DNS resolves domain names to IP addresses."},
  {q:"Which OSI layer is responsible for end-to-end segmentation and port numbers?",
   options:["Transport (Layer 4)","Network (Layer 3)","Session (Layer 5)","Data Link (Layer 2)"], answer:0,
   explain:"Layer 4 (Transport) handles segmentation and uses port numbers (TCP/UDP)."},
  {q:"A /30 subnet is commonly assigned to a point-to-point WAN link because it provides:",
   options:["2 usable host addresses","6 usable host addresses","0 usable addresses","254 usable addresses"], answer:0,
   explain:"/30 yields 2 usable hosts, ideal for a point-to-point link."},
  {q:"Plenum-rated cabling is required in air-handling spaces because it:",
   options:["Emits less toxic smoke when burning","Is faster","Carries PoE better","Is immune to EMI"], answer:0,
   explain:"Plenum cable has fire-resistant, low-smoke jacketing for airflow spaces."},
  {q:"Which addressing type sends a single packet to all hosts in a broadcast domain?",
   options:["Broadcast","Unicast","Multicast","Anycast"], answer:0,
   explain:"A broadcast is delivered to every host on the local segment."}
]});

/* ---------------- Domain 2: Network Implementation ---------------- */
Object.assign(EXAM_BANK, { "2": [
  {q:"A router has routes to the same network from OSPF and a static route. Which does it prefer by default, and why?",
   options:["The static route, due to lower administrative distance","The OSPF route, due to lower metric","Whichever came first","Neither; it drops both"], answer:0,
   explain:"Static routes have a lower administrative distance (more trusted) than OSPF by default."},
  {q:"Which routing protocol is used to exchange routes between autonomous systems on the internet?",
   options:["BGP","OSPF","RIP","EIGRP"], answer:0,
   explain:"BGP is the path-vector protocol used between autonomous systems."},
  {q:"A branch office of 25 hosts must share a single public IP for internet access. Which technology is used?",
   options:["PAT (NAT overload)","Static NAT one-to-one","DHCP reservation","802.1Q trunking"], answer:0,
   explain:"PAT maps many private hosts to one public IP using unique port numbers."},
  {q:"Traffic for VLAN 20 must reach VLAN 30. What is required?",
   options:["A router or Layer 3 switch (inter-VLAN routing)","A longer cable","A hub","DHCP snooping"], answer:0,
   explain:"VLANs are separate broadcast domains; routing (Layer 3) is needed to move traffic between them."},
  {q:"After adding a redundant link between two switches, users report the network is down with broadcast flooding. What was likely disabled?",
   options:["Spanning Tree Protocol","DHCP","DNS","QoS"], answer:0,
   explain:"Without STP, the redundant link creates a loop and broadcast storm."},
  {q:"A wireless AP and an IP phone need power but there are no nearby outlets. The switch should provide:",
   options:["PoE","QoS","NAT","STP"], answer:0,
   explain:"Power over Ethernet delivers power over the data cable to devices like APs and phones."},
  {q:"Users on a trunk between two switches can't access certain VLANs. You suspect a mismatch of the:",
   options:["Allowed VLANs / native VLAN on the trunk","IP subnet mask","DNS server","PoE budget"], answer:0,
   explain:"Trunk misconfiguration (allowed VLAN list or native VLAN mismatch) breaks VLAN connectivity."},
  {q:"A server NIC and switch port show poor throughput and many collisions. The likely cause is:",
   options:["A duplex mismatch","A DNS error","An expired certificate","A missing default route"], answer:0,
   explain:"Half/full duplex mismatches cause collisions and severe performance loss."},
  {q:"To bundle four 1 Gbps links into a single 4 Gbps logical link with redundancy, use:",
   options:["Link aggregation (LACP)","Spanning Tree blocking","NAT","VLAN pruning"], answer:0,
   explain:"LACP aggregates multiple physical links for greater bandwidth and failover."},
  {q:"Which feature should be enabled on access ports to prevent a connected switch from forming a trunk?",
   options:["Disable DTP / set ports to access mode","Enable jumbo frames","Raise the MTU","Enable PoE"], answer:0,
   explain:"Disabling dynamic trunking (DTP) and hardcoding access mode prevents switch-spoofing/trunk formation."},
  {q:"A WLAN must support high density and both 2.4/5 GHz with the latest speeds. Which standard should be deployed?",
   options:["Wi-Fi 6 (802.11ax)","802.11g","802.11a","802.11b"], answer:0,
   explain:"802.11ax (Wi-Fi 6) offers high efficiency/throughput on 2.4 and 5 GHz."},
  {q:"Enterprise Wi-Fi should authenticate each user individually with unique credentials. Which mode is required?",
   options:["WPA3-Enterprise (802.1X/RADIUS)","WPA3-Personal (PSK)","WEP","Open"], answer:0,
   explain:"Enterprise mode uses 802.1X and RADIUS for per-user authentication."},
  {q:"A point-to-point wireless bridge connects two buildings. Which antenna type is most appropriate?",
   options:["Directional (e.g., Yagi/parabolic)","Omnidirectional","No antenna","A dipole for 360° coverage"], answer:0,
   explain:"Directional antennas focus the signal for long-distance point-to-point links."},
  {q:"A DHCP reservation is configured so a printer always gets the same address. The reservation maps the IP to the printer's:",
   options:["MAC address","Hostname only","VLAN","Cable"], answer:0,
   explain:"Reservations bind a specific IP to a device's MAC address."},
  {q:"Which document/standard defines the wire color order when terminating an RJ45 jack?",
   options:["T568A/T568B","802.1Q","802.11ax","RFC 1918"], answer:0,
   explain:"T568A and T568B define the twisted-pair pin/pair wiring order."},
  {q:"To trace a specific unlabeled cable in a bundle at the patch panel, a technician should use a:",
   options:["Tone generator and probe","Protocol analyzer","Port scanner","Multimeter only"], answer:0,
   explain:"A toner and probe let you identify and trace a specific cable run."},
  {q:"Devices in a rack need consolidated, monitored power. Install a:",
   options:["PDU","UPS battery only","Patch panel","Media converter"], answer:0,
   explain:"A Power Distribution Unit distributes (and often monitors) power to rack equipment."},
  {q:"A server room's cooling fails during a heat wave. The BEST preventive control is:",
   options:["Proper HVAC and environmental monitoring","More bandwidth","A stronger firewall","Longer cables"], answer:0,
   explain:"HVAC with temperature/humidity monitoring prevents heat-related equipment failures."},
  {q:"Which technology tags frames so multiple VLANs traverse a single inter-switch link?",
   options:["802.1Q","802.3af","802.1X","802.11ac"], answer:0,
   explain:"802.1Q tagging carries multiple VLANs across a trunk."},
  {q:"A default route on a router is written as:",
   options:["0.0.0.0/0","255.255.255.255/32","127.0.0.1/8","169.254.0.0/16"], answer:0,
   explain:"0.0.0.0/0 is the default route used when no specific route matches."},
  {q:"BPDU Guard is applied to access ports to:",
   options:["Shut the port if it receives BPDUs (a rogue switch)","Increase throughput","Enable PoE","Assign DNS"], answer:0,
   explain:"BPDU Guard disables edge ports that unexpectedly receive spanning-tree BPDUs."},
  {q:"Which best describes static routing's main disadvantage in a large, changing network?",
   options:["It doesn't adapt automatically to failures/changes","It uses excessive CPU","It floods the network","It requires WPA3"], answer:0,
   explain:"Static routes must be manually maintained and don't react to topology changes."},
  {q:"An organization wants seamless client roaming across many APs. Configure them with:",
   options:["The same SSID (an ESS)","Unique SSIDs per AP","Ad-hoc mode","Different security types each"], answer:0,
   explain:"A common SSID across APs (ESS) enables roaming."},
  {q:"Jumbo frames are enabled on a storage network primarily to:",
   options:["Reduce overhead for large data transfers","Encrypt traffic","Shrink packet size","Disable VLANs"], answer:0,
   explain:"Larger MTU (jumbo frames) improves efficiency for bulk transfers like iSCSI/NAS."},
  {q:"Which routing protocol is a distance-vector protocol limited to 15 hops?",
   options:["RIP","OSPF","BGP","IS-IS"], answer:0,
   explain:"RIP is distance-vector with a 15-hop maximum (16 = unreachable)."},
  {q:"A technician needs to segment guest Wi-Fi from the corporate LAN. The BEST approach is:",
   options:["Place guest traffic on a separate VLAN","Use the same VLAN with a strong password","Disable DHCP","Increase transmit power"], answer:0,
   explain:"A dedicated guest VLAN isolates guest traffic from corporate resources."}
]});

/* ---------------- Domain 3: Network Operations ---------------- */
Object.assign(EXAM_BANK, { "3": [
  {q:"A team needs to track which IP addresses are assigned across all subnets. The BEST tool is:",
   options:["IPAM","A rack diagram","A protocol analyzer","A cable tester"], answer:0,
   explain:"IP Address Management (IPAM) centrally tracks IP allocations and subnets."},
  {q:"Which SNMP version should be used to ensure management traffic is authenticated and encrypted?",
   options:["SNMPv3","SNMPv1","SNMPv2c","SNMPv0"], answer:0,
   explain:"SNMPv3 adds authentication and encryption; earlier versions use plaintext community strings."},
  {q:"A device sends an unsolicited alert to the monitoring system when a link fails. This is an SNMP:",
   options:["Trap","Get request","Walk","Community string"], answer:0,
   explain:"SNMP traps are device-initiated notifications sent to the manager."},
  {q:"To correlate events across many devices accurately, all devices must have:",
   options:["Synchronized time via NTP","The same IP address","The same MAC","Identical hostnames"], answer:0,
   explain:"Accurate, synchronized clocks (NTP) are required to correlate log timestamps."},
  {q:"A recovery site is fully equipped and can take over operations within minutes. This is a:",
   options:["Hot site","Cold site","Warm site","Mobile trailer only"], answer:0,
   explain:"A hot site is fully operational and ready for near-immediate failover."},
  {q:"A business can tolerate losing at most 1 hour of data. This defines the:",
   options:["RPO","RTO","MTBF","MTTR"], answer:0,
   explain:"RPO is the maximum acceptable data loss in time, driving backup frequency."},
  {q:"To provide a redundant default gateway so hosts stay connected if one router fails, deploy:",
   options:["VRRP/HSRP","STP","NAT","DHCP snooping"], answer:0,
   explain:"First Hop Redundancy Protocols (VRRP/HSRP) give hosts a resilient virtual gateway."},
  {q:"Clients on VLAN 40 aren't getting IP addresses; the DHCP server is on another subnet. What is needed on the VLAN 40 gateway?",
   options:["A DHCP relay (IP helper)","A default route only","A trunk port","A longer lease"], answer:0,
   explain:"A DHCP relay forwards broadcast DHCP requests to a server on another subnet."},
  {q:"A user can reach sites by IP but not by name. Which service should you check?",
   options:["DNS","DHCP","NTP","SNMP"], answer:0,
   explain:"Name resolution failures point to DNS problems."},
  {q:"Which DNS record type is queried to find a domain's mail servers?",
   options:["MX","A","CNAME","PTR"], answer:0,
   explain:"MX records identify the mail exchangers for a domain."},
  {q:"A reverse DNS lookup (IP to name) uses which record type?",
   options:["PTR","A","MX","TXT"], answer:0,
   explain:"PTR records map an IP address back to a hostname for reverse lookups."},
  {q:"An organization documents each device's position by rack unit for maintenance. This is a:",
   options:["Rack diagram","Logical diagram","Wiring standard","Routing table"], answer:0,
   explain:"Rack diagrams record equipment U-positions within racks."},
  {q:"Before applying firmware updates fleet-wide, the BEST practice is to:",
   options:["Test on a subset and have a rollback plan","Apply to all devices at once","Skip backups","Disable monitoring"], answer:0,
   explain:"Test changes and prepare rollback to avoid widespread outages."},
  {q:"A configuration backup of switches and routers primarily enables:",
   options:["Rapid restore after failure or bad changes","Faster routing","More bandwidth","Encryption"], answer:0,
   explain:"Config backups allow quick recovery to a known-good state."},
  {q:"NetFlow/flow data is most useful for:",
   options:["Identifying top talkers and traffic patterns","Terminating fiber","Assigning IPs","Polishing connectors"], answer:0,
   explain:"Flow data reveals conversations and volumes for capacity and security analysis."},
  {q:"A performance baseline is valuable because it:",
   options:["Defines 'normal' so anomalies stand out","Encrypts traffic","Assigns VLANs","Provides PoE"], answer:0,
   explain:"Baselines establish normal behavior, making deviations easy to detect."},
  {q:"SLAAC allows an IPv6 host to configure its address using information from a:",
   options:["Router Advertisement","DHCP Offer","DNS PTR record","MAC table"], answer:0,
   explain:"SLAAC uses ICMPv6 Router Advertisements to derive an address without a DHCP server."},
  {q:"Which remote access method provides a secure encrypted CLI session?",
   options:["SSH","Telnet","HTTP","TFTP"], answer:0,
   explain:"SSH encrypts remote command-line sessions; Telnet is plaintext."},
  {q:"A full-tunnel client VPN is chosen so that:",
   options:["All user traffic is inspected/secured through the corporate network","Only local traffic is secured","No traffic is encrypted","DNS is bypassed"], answer:0,
   explain:"Full tunnel routes all client traffic through the VPN for inspection and protection."},
  {q:"Which Syslog severity level is the most critical?",
   options:["0 – Emergency","7 – Debug","5 – Notice","3 – Error"], answer:0,
   explain:"Syslog severity 0 (Emergency) is the most severe; 7 (Debug) is the least."},
  {q:"A company keeps a documented, tested process to resume operations after a major outage. This is a:",
   options:["Disaster recovery plan","Acceptable use policy","Wiring standard","Routing table"], answer:0,
   explain:"A DR plan defines how to restore operations after a disaster."},
  {q:"An A record is used to:",
   options:["Map a hostname to an IPv4 address","Map to an IPv6 address","Identify a mail server","Create an alias"], answer:0,
   explain:"A records map hostnames to IPv4 addresses (AAAA for IPv6)."},
  {q:"Which tool centrally aggregates and correlates logs and generates security alerts?",
   options:["SIEM","IPAM","Cable tester","Tone generator"], answer:0,
   explain:"A SIEM aggregates logs and correlates events for alerting."},
  {q:"A DHCP scope's exclusion range is used to:",
   options:["Keep specific addresses from being leased dynamically","Encrypt leases","Speed up DNS","Create VLANs"], answer:0,
   explain:"Exclusions prevent certain addresses (e.g., static servers) from being handed out."},
  {q:"Life-cycle planning should replace hardware that has reached:",
   options:["End of support (no more patches)","Its first year of use","Half its warranty","Peak performance"], answer:0,
   explain:"End-of-support hardware receives no security updates and should be replaced."}
]});

/* ---------------- Domain 4: Network Security ---------------- */
Object.assign(EXAM_BANK, { "4": [
  {q:"An attacker overflows a switch's MAC table so it floods frames out all ports. Which feature stops this?",
   options:["Port security","STP","QoS","Jumbo frames"], answer:0,
   explain:"Port security limits the number of MAC addresses per port, preventing CAM-table flooding."},
  {q:"Which switch feature validates ARP replies against DHCP snooping bindings to stop ARP spoofing?",
   options:["Dynamic ARP Inspection","BPDU Guard","LACP","PoE"], answer:0,
   explain:"Dynamic ARP Inspection (DAI) drops invalid/spoofed ARP packets."},
  {q:"To prevent a rogue DHCP server from assigning bad configs, enable:",
   options:["DHCP snooping","Port mirroring","Jumbo frames","STP PortFast only"], answer:0,
   explain:"DHCP snooping only trusts DHCP server replies from designated trusted ports."},
  {q:"A DDoS attack against a web server most directly threatens which security goal?",
   options:["Availability","Confidentiality","Integrity","Non-repudiation"], answer:0,
   explain:"DoS/DDoS attacks aim to make the service unavailable."},
  {q:"Which is a strong mitigation against VLAN hopping via switch spoofing?",
   options:["Disable DTP and hardcode access ports","Enable jumbo frames","Raise transmit power","Shorten cables"], answer:0,
   explain:"Disabling dynamic trunk negotiation prevents attackers from forming a trunk."},
  {q:"An employee lets a stranger follow them through a badge-controlled door. This is:",
   options:["Tailgating","Vishing","Smishing","Phishing"], answer:0,
   explain:"Tailgating is physically following an authorized person through access control."},
  {q:"Which authentication approach requires two different factor types?",
   options:["Password plus a hardware token code","Two passwords","A password entered twice","Two security questions"], answer:0,
   explain:"MFA combines factors from different categories (knowledge + possession)."},
  {q:"A network device should be managed securely. Which change should be made?",
   options:["Replace Telnet with SSH","Enable Telnet for convenience","Use default credentials","Open all ports"], answer:0,
   explain:"SSH encrypts management sessions, unlike plaintext Telnet."},
  {q:"Which centralized service authenticates users for network access with 802.1X?",
   options:["RADIUS","DNS","NTP","DHCP"], answer:0,
   explain:"802.1X uses a RADIUS server to authenticate users/devices before granting access."},
  {q:"A NAC solution checks a laptop's patch level and antivirus status before allowing access. This is enforcing:",
   options:["Device posture / compliance","IP addressing","Cable standards","VLAN tagging only"], answer:0,
   explain:"NAC evaluates device posture/compliance to control network admission."},
  {q:"Isolating IoT cameras on their own VLAN with restricted ACLs is an example of:",
   options:["Segmentation to contain risk","Trunking all traffic","Disabling STP","Static routing"], answer:0,
   explain:"Segmentation limits exposure so a compromised device can't reach the whole network."},
  {q:"A DMZ (screened subnet) is used to host:",
   options:["Public-facing servers separated from the internal LAN","Offline backups","Internal databases only","The DHCP scope"], answer:0,
   explain:"A DMZ isolates internet-facing services from the trusted internal network."},
  {q:"Which regulation applies to organizations that store or process payment card data?",
   options:["PCI DSS","HIPAA","FERPA","GLBA"], answer:0,
   explain:"PCI DSS governs the secure handling of payment card data."},
  {q:"An IDS differs from an IPS because an IDS:",
   options:["Only detects and alerts (out-of-band)","Blocks traffic inline","Assigns IP addresses","Routes between VLANs"], answer:0,
   explain:"An IDS detects and alerts; an IPS is inline and can actively block."},
  {q:"A honeypot is deployed primarily to:",
   options:["Lure and study attackers","Speed up the network","Assign IP addresses","Encrypt backups"], answer:0,
   explain:"Honeypots are decoys used to attract and observe attacker behavior."},
  {q:"Firewall rule sets typically end with an:",
   options:["Implicit deny","Implicit allow","Automatic NAT","STP block"], answer:0,
   explain:"Most firewalls apply an implicit deny to anything not explicitly permitted."},
  {q:"The strongest general defense against social engineering is:",
   options:["Security awareness training","A faster firewall","More bandwidth","Longer cables"], answer:0,
   explain:"Educated users are the best defense against manipulation-based attacks."},
  {q:"Applying least privilege on network devices means administrators:",
   options:["Get only the access their role requires","Share one superuser account","Have full access to everything","Use no authentication"], answer:0,
   explain:"Least privilege grants only the access necessary for each role."},
  {q:"An attacker floods a target using many compromised hosts. This botnet-driven attack is a:",
   options:["DDoS","Single DoS from one host","Phishing campaign","MAC flood only"], answer:0,
   explain:"A distributed attack using many hosts (a botnet) is a DDoS."},
  {q:"Which control prevents unauthorized devices from connecting to unused wall jacks?",
   options:["Disable unused switch ports","Enable jumbo frames","Increase PoE budget","Use longer cables"], answer:0,
   explain:"Administratively shutting unused ports blocks rogue device connections."},
  {q:"An ACL on a router is evaluated:",
   options:["Top-down until a match, then stop","Bottom-up only","In random order","Only for outbound traffic"], answer:0,
   explain:"ACLs are processed top-down; the first matching rule applies."},
  {q:"Content/URL filtering at the network edge is used to:",
   options:["Block access to malicious or disallowed sites","Assign VLANs","Terminate fiber","Provide DHCP"], answer:0,
   explain:"Content filters restrict access to risky or policy-violating websites."}
]});

/* ---------------- Domain 5: Network Troubleshooting ---------------- */
Object.assign(EXAM_BANK, { "5": [
  {q:"Following the CompTIA methodology, what should you do FIRST?",
   options:["Identify the problem","Establish a theory of probable cause","Implement the solution","Document the outcome"], answer:0,
   explain:"Step 1 is identifying the problem by gathering information."},
  {q:"After you implement a fix and confirm full functionality, the next step is to:",
   options:["Document findings, actions, and outcomes","Establish a new theory","Escalate to the vendor","Replace the hardware"], answer:0,
   explain:"The final step is documenting the problem, solution, and lessons learned."},
  {q:"A user reports slow transfers; you find CRC errors climbing on the switch port. The MOST likely cause is:",
   options:["A physical issue (bad cable, EMI, or duplex mismatch)","A DNS misconfiguration","A missing default route","A DHCP scope error"], answer:0,
   explain:"CRC/frame errors indicate physical-layer problems, not logical config."},
  {q:"Which command would you use FIRST to test basic reachability to a host?",
   options:["ping","nslookup","netstat","route print"], answer:0,
   explain:"ping uses ICMP echo to verify reachability."},
  {q:"Users can browse by IP but not by name. Which command helps confirm a DNS issue?",
   options:["nslookup / dig","ping -t only","arp -a","ipconfig /all only"], answer:0,
   explain:"nslookup/dig query DNS directly to confirm name-resolution problems."},
  {q:"A workstation shows 'Duplicate IP address detected.' The cause is:",
   options:["Another device is using the same IP","A DNS record is wrong","The gateway is down","STP is disabled"], answer:0,
   explain:"Two devices sharing an IP triggers a conflict and intermittent connectivity."},
  {q:"A PC can reach local hosts but not the internet. The MOST likely misconfiguration is the:",
   options:["Default gateway","DNS suffix","MAC address","Cable category"], answer:0,
   explain:"Without a correct default gateway, a host can't reach remote networks."},
  {q:"You need to see the hop-by-hop path and where latency spikes toward a server. Use:",
   options:["traceroute / tracert","ping only","arp","netstat"], answer:0,
   explain:"traceroute/tracert reveals each hop and where delays occur."},
  {q:"An interface shows 'runts' and 'giants.' These indicate frames that are:",
   options:["Smaller or larger than allowed","Encrypted","On the wrong VLAN","Routed incorrectly"], answer:0,
   explain:"Runts are undersized and giants oversized frames — often errors or MTU issues."},
  {q:"After adding a second switch link, the whole LAN slows to a crawl with constant broadcasts. The cause is likely a:",
   options:["Switching loop (STP not working)","DNS outage","Certificate expiry","Bad DHCP lease"], answer:0,
   explain:"A Layer 2 loop without STP causes broadcast storms."},
  {q:"VoIP calls have choppy audio though bandwidth is fine. The MOST likely culprit is:",
   options:["Jitter (variable delay)","A duplicate IP","A DNS error","A bad cable category"], answer:0,
   explain:"Jitter (variation in delay) degrades real-time audio even with adequate bandwidth."},
  {q:"A remote user's Wi-Fi is slow only when far from the AP. The cause is:",
   options:["Low signal strength / attenuation","A routing loop","A DNS failure","An IP conflict"], answer:0,
   explain:"Weak signal from distance/obstacles lowers data rates."},
  {q:"Two adjacent APs on channel 6 in 2.4 GHz cause slowdowns. The fix is to:",
   options:["Assign non-overlapping channels (1/6/11)","Set both to channel 6","Disable encryption","Raise power to maximum"], answer:0,
   explain:"Co-channel interference is reduced by using non-overlapping channels."},
  {q:"To capture and inspect the exact packets during a handshake failure, use a:",
   options:["Protocol analyzer (packet capture)","Cable tester","Tone generator","Multimeter"], answer:0,
   explain:"A protocol analyzer (e.g., Wireshark) captures packets for detailed analysis."},
  {q:"To verify a newly terminated cable has correct pinout and no shorts/opens, use a:",
   options:["Cable tester","Port scanner","SIEM","DHCP server"], answer:0,
   explain:"A cable tester checks continuity, wiring order, and faults."},
  {q:"Which command displays a Windows host's full IP configuration including DNS and gateway?",
   options:["ipconfig /all","ping","tracert","arp -d"], answer:0,
   explain:"ipconfig /all shows the complete IP configuration on Windows."},
  {q:"An SFP shows no link and errors on a fiber run. The BEST first steps are to:",
   options:["Reseat/replace the transceiver and clean the end-faces","Assign a new IP","Add it to a VLAN","Increase the PoE budget"], answer:0,
   explain:"Faulty or dirty transceivers cause fiber link issues; reseat/clean or replace."},
  {q:"Several PoE devices won't power on after adding cameras. The likely cause is:",
   options:["Exceeded PoE power budget","A DNS outage","A routing loop","A duplicate IP"], answer:0,
   explain:"If total PoE demand exceeds the switch budget, some devices won't power up."},
  {q:"A port repeatedly transitions up/down. This 'flapping' most often indicates:",
   options:["A faulty cable or failing hardware/transceiver","A DNS error","A missing route","A DHCP exclusion"], answer:0,
   explain:"Interface flapping usually points to physical cabling or hardware faults."},
  {q:"To display active connections and listening ports on a host, use:",
   options:["netstat","route","arp","dig"], answer:0,
   explain:"netstat lists active connections and listening ports."},
  {q:"A device is unexpectedly isolated from its peers; you discover it is in the wrong:",
   options:["VLAN","DNS zone","Time zone","Rack unit"], answer:0,
   explain:"An incorrect VLAN assignment isolates a device from its intended network."},
  {q:"Cable runs longer than 100 meters on twisted pair cause:",
   options:["Attenuation and connectivity problems","Faster speeds","Better security","More IPs"], answer:0,
   explain:"Exceeding 100 m leads to signal attenuation and link failures."},
  {q:"A native VLAN mismatch on a trunk between two switches causes:",
   options:["Traffic to cross into the wrong VLAN","Faster throughput","More IP addresses","Stronger encryption"], answer:0,
   explain:"Mismatched native VLANs misdirect untagged traffic, breaking connectivity."},
  {q:"To locate a break in a long fiber run and its distance, a technician uses an:",
   options:["OTDR","OS fingerprinting tool","IPAM system","SNMP walk"], answer:0,
   explain:"An OTDR (Optical Time-Domain Reflectometer) locates faults and measures distance on fiber."},
  {q:"A user's throughput is capped and the link shows near 100% utilization. The BEST remedies are:",
   options:["Apply QoS and/or add capacity","Disable logging","Shorten the cable","Remove all VLANs"], answer:0,
   explain:"QoS prioritizes critical traffic; adding bandwidth relieves saturation."},
  {q:"The 'show interface' command on a switch is MOST useful for viewing:",
   options:["Port status, errors, and counters","DNS records","DHCP leases","Routing protocols only"], answer:0,
   explain:"'show interface' reveals status and error counters vital to troubleshooting."},
  {q:"A technician suspects EMI is corrupting data on a copper run near heavy machinery. The BEST fix is:",
   options:["Use shielded cabling (STP) or reroute/ use fiber","Use a longer cable","Lower the MTU","Disable STP"], answer:0,
   explain:"Shielded cabling or fiber avoids EMI-induced errors near electrical noise."},
  {q:"A newly connected access port that should be a trunk isn't passing VLANs. Check whether the port is:",
   options:["Configured as access instead of trunk","Powered by PoE","On the right rack","Using fiber"], answer:0,
   explain:"A trunk must be configured as such; an access port carries only one VLAN."},
  {q:"Which tool would you use to discover which TCP ports are open on a server?",
   options:["A port scanner (e.g., Nmap)","A cable tester","A tone generator","An OTDR"], answer:0,
   explain:"Port scanners enumerate open ports/services on a host."},
  {q:"A user reports intermittent connectivity; pings show occasional packet loss. A good next step is to:",
   options:["Check cabling/interface errors and utilization along the path","Reinstall the OS","Replace the monitor","Change the wallpaper"], answer:0,
   explain:"Intermittent loss warrants checking physical errors, utilization, and the path (e.g., traceroute)."}
]});

