/* ===========================================================
   Network+ N10-009 — Flashcard decks (Quizlet-style)
   FLASHCARDS keyed by section number. Each card: { t: term, d: definition }
   =========================================================== */
const FLASHCARDS = {
"1": [
  {t:"OSI Model", d:"7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application (1–7)."},
  {t:"Layer 2 – Data Link", d:"Uses MAC addresses and frames. Switches operate here."},
  {t:"Layer 3 – Network", d:"Logical addressing (IP) and routing. Routers operate here."},
  {t:"TCP", d:"Connection-oriented, reliable transport using the SYN, SYN-ACK, ACK handshake."},
  {t:"UDP", d:"Connectionless, best-effort transport. Low overhead, used for VoIP/streaming/DNS."},
  {t:"Common ports", d:"FTP 20/21, SSH 22, Telnet 23, SMTP 25, DNS 53, DHCP 67/68, HTTP 80, HTTPS 443, RDP 3389."},
  {t:"SNMP / NTP ports", d:"SNMP uses 161/162; NTP uses 123."},
  {t:"Private IP ranges (RFC 1918)", d:"10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16."},
  {t:"APIPA", d:"169.254.0.0/16 self-assigned address when a client can't reach a DHCP server."},
  {t:"Loopback", d:"127.0.0.1 (IPv4) / ::1 (IPv6) — refers to the local host."},
  {t:"Subnet mask / CIDR", d:"Separates network bits from host bits. /24 = 255.255.255.0."},
  {t:"Usable hosts formula", d:"2^(host bits) − 2 (subtract network and broadcast addresses)."},
  {t:"Unicast / Broadcast / Multicast", d:"One-to-one / one-to-all-on-subnet / one-to-a-group."},
  {t:"MAC address", d:"48-bit Layer 2 hardware address; first half is the OUI (vendor)."},
  {t:"ARP", d:"Resolves an IP address to a MAC address on a local network."},
  {t:"Cat 5e / 6 / 6a", d:"Twisted-pair: 5e=1 Gbps, 6=10 Gbps to ~55 m, 6a=10 Gbps to 100 m."},
  {t:"UTP vs STP", d:"Unshielded vs Shielded twisted pair; STP reduces EMI/crosstalk."},
  {t:"Plenum cable", d:"Fire-resistant, low-smoke jacketing required in air-handling spaces."},
  {t:"Single-mode vs Multimode fiber", d:"SMF = long distance (small core, laser); MMF = shorter runs (larger core, LED)."},
  {t:"Fiber connectors", d:"LC, SC, ST, MTP/MPO. APC polish reduces back reflection vs UPC."},
  {t:"Transceivers (SFP/SFP+/QSFP)", d:"Hot-swappable modules: SFP=1G, SFP+=10G, QSFP=40/100G."},
  {t:"Wi-Fi bands", d:"2.4 GHz = longer range/slower; 5 GHz = faster/shorter; 6 GHz = Wi-Fi 6E."},
  {t:"Non-overlapping 2.4 GHz channels", d:"Channels 1, 6, and 11."},
  {t:"802.11 standards", d:"a/b/g/n(Wi-Fi 4)/ac(Wi-Fi 5)/ax(Wi-Fi 6). ax works on 2.4 & 5 GHz."},
  {t:"Topologies", d:"Star (central switch), mesh (all-to-all), bus, ring, hub-and-spoke."},
  {t:"Spine-and-leaf", d:"Data-center architecture giving consistent low-latency any-to-any connectivity."},
  {t:"Cloud service models", d:"IaaS (infra), PaaS (platform), SaaS (software) — provider manages progressively more."},
  {t:"Cloud deployment models", d:"Public, Private, Hybrid, Community."},
  {t:"SDN", d:"Software-Defined Networking separates the control plane from the data plane."},
  {t:"VXLAN", d:"Tunnels Layer 2 over Layer 3; 24-bit VNI allows ~16 million segments."},
  {t:"IPv6", d:"128-bit addresses. FE80::/10 = link-local; SLAAC autoconfigures addresses."},
  {t:"MTU / Jumbo frames", d:"Max transmission unit (default 1500). Jumbo frames (~9000) cut overhead."}
],
"2": [
  {t:"Static routing", d:"Manually configured routes; simple but doesn't adapt to changes automatically."},
  {t:"Dynamic routing", d:"Protocols share and update routes automatically (OSPF, EIGRP, BGP, RIP)."},
  {t:"OSPF", d:"Link-state interior gateway protocol using cost as its metric."},
  {t:"BGP", d:"Path-vector protocol that routes between autonomous systems (the internet)."},
  {t:"Administrative distance", d:"Trust ranking used to choose between routes from different sources."},
  {t:"NAT", d:"Maps private addresses to public IP(s), conserving public addresses."},
  {t:"PAT", d:"NAT overload — many hosts share one public IP, distinguished by port number."},
  {t:"VLAN", d:"Logical segmentation of a switch into separate broadcast domains."},
  {t:"802.1Q", d:"Standard that tags frames with VLAN IDs across trunk links."},
  {t:"Trunk vs Access port", d:"Trunk carries multiple tagged VLANs; access port carries one VLAN."},
  {t:"Native VLAN", d:"The untagged VLAN on an 802.1Q trunk; must match on both ends."},
  {t:"STP", d:"Spanning Tree Protocol prevents Layer 2 loops by blocking redundant paths."},
  {t:"BPDU Guard", d:"Disables an access port if it receives BPDUs (a rogue switch)."},
  {t:"LACP / Link aggregation", d:"Bundles multiple links for more bandwidth and redundancy."},
  {t:"Duplex mismatch", d:"One side half, other full duplex — causes collisions and poor performance."},
  {t:"PoE / PoE+", d:"Power over Ethernet delivers power to APs, phones, cameras over the data cable."},
  {t:"Inter-VLAN routing", d:"Routing (Layer 3 switch/router) required to move traffic between VLANs."},
  {t:"Wireless modes", d:"Infrastructure (via AP) vs ad-hoc (peer-to-peer)."},
  {t:"BSS / ESS", d:"BSS = one AP's coverage; ESS = multiple APs sharing an SSID for roaming."},
  {t:"MIMO / MU-MIMO", d:"Multiple antennas/streams to boost wireless throughput and capacity."},
  {t:"WPA3", d:"Latest, most secure Wi-Fi encryption; Personal uses SAE, Enterprise uses 802.1X."},
  {t:"WPA2/WPA3-Enterprise", d:"Per-user authentication via 802.1X and a RADIUS server."},
  {t:"Antenna types", d:"Omnidirectional (360°) vs directional (Yagi/parabolic) for point-to-point."},
  {t:"Network types", d:"LAN, WAN, MAN, PAN, WLAN, SAN, CAN — by size/purpose."},
  {t:"MDF / IDF", d:"Main Distribution Frame (central) connects to Intermediate DFs (per area/floor)."},
  {t:"Patch panel", d:"Termination point where horizontal cabling connects in the wiring closet."},
  {t:"Punch-down block (66/110)", d:"Terminates and cross-connects twisted-pair wiring."},
  {t:"UPS vs Generator", d:"UPS = short-term battery for outages; generator = longer-term power."},
  {t:"PDU", d:"Power Distribution Unit distributes (and may monitor) power to rack equipment."},
  {t:"Hot/cold aisle", d:"Data-center layout that separates hot exhaust from cold intake air."}
],
"3": [
  {t:"Physical vs Logical diagram", d:"Physical = device locations/cabling; logical = IP/VLAN/data flow."},
  {t:"IPAM", d:"IP Address Management — tracks IP allocations, subnets, and DNS/DHCP data."},
  {t:"Rack diagram", d:"Documents equipment positions (U) within a rack."},
  {t:"SNMP", d:"Monitors/manages devices. v3 adds authentication and encryption."},
  {t:"SNMP trap", d:"Unsolicited alert sent from a device to the SNMP manager."},
  {t:"Syslog", d:"Centralized logging protocol; severity 0 (emergency) to 7 (debug)."},
  {t:"SIEM", d:"Aggregates and correlates logs/events to generate security alerts."},
  {t:"NetFlow", d:"Flow data showing top talkers and traffic patterns for analysis."},
  {t:"Baseline", d:"A record of normal performance used to detect anomalies."},
  {t:"RTO", d:"Recovery Time Objective — max acceptable time to restore a service."},
  {t:"RPO", d:"Recovery Point Objective — max acceptable data loss (in time)."},
  {t:"MTBF / MTTR", d:"Mean Time Between Failures (reliability) / Mean Time To Repair (recovery speed)."},
  {t:"Hot/Warm/Cold site", d:"Recovery sites: hot = ready now, warm = partial, cold = space/power only."},
  {t:"HSRP / VRRP", d:"First Hop Redundancy Protocols providing a redundant default gateway."},
  {t:"DHCP (DORA)", d:"Discover, Offer, Request, Acknowledge — leases IP config to clients."},
  {t:"DHCP relay (IP helper)", d:"Forwards DHCP broadcasts to a server on a different subnet."},
  {t:"DHCP scope / reservation", d:"Scope = pool of leasable IPs; reservation ties an IP to a MAC."},
  {t:"DHCP exclusion", d:"Addresses within a scope kept from being dynamically assigned."},
  {t:"DNS", d:"Resolves names to IPs (port 53). Recursive resolvers do the full lookup."},
  {t:"DNS record types", d:"A (IPv4), AAAA (IPv6), MX (mail), CNAME (alias), PTR (reverse), TXT."},
  {t:"NTP", d:"Synchronizes clocks; critical for logs, certificates, and Kerberos. Uses stratum levels."},
  {t:"SLAAC", d:"IPv6 hosts auto-configure addresses using Router Advertisements (no DHCP)."},
  {t:"EUI-64", d:"Derives the IPv6 interface ID from the device's 48-bit MAC address."},
  {t:"Site-to-site VPN", d:"Securely connects two entire networks over the internet."},
  {t:"Client (remote-access) VPN", d:"Connects a single device to the network; full vs split tunnel."},
  {t:"IPsec", d:"Encrypts/authenticates IP traffic at Layer 3; common for VPNs."},
  {t:"SSH / RDP", d:"SSH = encrypted CLI (22); RDP = remote desktop (3389)."},
  {t:"Configuration management", d:"Baselines, backups, and version control of device configs."},
  {t:"Life-cycle management", d:"Planning for EOL (end of life) and EOS (end of support) hardware."},
  {t:"Disaster recovery plan", d:"Documented, tested process to resume operations after a major outage."}
],
"4": [
  {t:"CIA Triad", d:"Confidentiality, Integrity, Availability — core security goals."},
  {t:"Defense in depth", d:"Layering multiple controls so no single failure exposes everything."},
  {t:"Least privilege", d:"Give users/devices only the access their role requires."},
  {t:"Zero Trust", d:"Never trust, always verify — authenticate every request regardless of location."},
  {t:"AAA (RADIUS/TACACS+)", d:"Centralized Authentication, Authorization, and Accounting for access."},
  {t:"802.1X", d:"Port-based access control: supplicant, authenticator, and RADIUS server."},
  {t:"MFA", d:"Multifactor authentication combining factor types (know/have/are)."},
  {t:"NAC", d:"Network Access Control checks device posture/identity before granting access."},
  {t:"IDS vs IPS", d:"IDS detects and alerts (out-of-band); IPS blocks inline."},
  {t:"Honeypot", d:"A decoy system used to attract and study attackers."},
  {t:"Segmentation / DMZ", d:"Isolating zones (e.g., a screened subnet) to contain risk and host public services."},
  {t:"DoS / DDoS", d:"Overwhelming a target to harm availability; DDoS uses a botnet of many hosts."},
  {t:"VLAN hopping", d:"Reaching other VLANs via double-tagging or switch spoofing. Mitigate: harden native VLAN, disable DTP."},
  {t:"MAC flooding", d:"Overflows the switch CAM table so it floods traffic. Mitigate: port security."},
  {t:"ARP poisoning", d:"Spoofed ARP replies redirect traffic (on-path). Mitigate: Dynamic ARP Inspection."},
  {t:"DNS poisoning", d:"Corrupts name resolution to send users to malicious IPs."},
  {t:"Rogue DHCP", d:"Unauthorized DHCP server handing out bad configs. Mitigate: DHCP snooping."},
  {t:"Rogue AP / Evil twin", d:"Unauthorized/impersonating access point used to intercept clients."},
  {t:"DHCP snooping", d:"Only trusts DHCP server replies from designated trusted ports."},
  {t:"Dynamic ARP Inspection", d:"Validates ARP packets against DHCP snooping bindings to stop spoofing."},
  {t:"Port security", d:"Limits allowed MAC addresses per switch port to stop flooding/rogue devices."},
  {t:"Social engineering", d:"Manipulating people (phishing, tailgating, pretexting). Defense: awareness training."},
  {t:"Phishing / Tailgating", d:"Fraudulent messages / following someone through a secure door."},
  {t:"Malware", d:"Malicious software (virus, worm, ransomware, trojan). Defense: EDR + patching."},
  {t:"ACL", d:"Access Control List permits/denies traffic; processed top-down with implicit deny."},
  {t:"Firewall rule order", d:"Evaluated top-down; first match wins; implicit deny at the end."},
  {t:"Device hardening", d:"Change defaults, disable unused ports/services, use SSH not Telnet."},
  {t:"PCI DSS / HIPAA", d:"Regulations for payment card data (PCI DSS) and health data (HIPAA)."},
  {t:"Content/URL filtering", d:"Blocks access to malicious or disallowed websites."}
],
"5": [
  {t:"Troubleshooting step 1", d:"Identify the problem (gather info, question users, note recent changes)."},
  {t:"Troubleshooting order", d:"Identify → theory → test theory → plan → implement → verify → document."},
  {t:"Final troubleshooting step", d:"Document findings, actions, and outcomes."},
  {t:"ping", d:"Tests reachability using ICMP echo request/reply."},
  {t:"traceroute / tracert", d:"Shows the hop-by-hop path and where latency/loss occurs."},
  {t:"nslookup / dig", d:"Query DNS to resolve names and troubleshoot DNS issues."},
  {t:"ipconfig / ifconfig / ip", d:"Display and manage a host's IP configuration."},
  {t:"netstat", d:"Shows active connections and listening ports."},
  {t:"arp", d:"Displays/edits the IP-to-MAC address mapping table."},
  {t:"show interface", d:"Displays port status, errors, and counters on a switch/router."},
  {t:"CRC errors", d:"Frame check errors indicating physical issues (bad cable, EMI, duplex)."},
  {t:"Runts / Giants", d:"Frames smaller / larger than the allowed size."},
  {t:"Interface flapping", d:"A port repeatedly going up/down — often a cable or hardware fault."},
  {t:"Duplex mismatch", d:"Half/full mismatch causing collisions and slow performance."},
  {t:"IP address conflict", d:"Two devices sharing an IP, causing intermittent connectivity."},
  {t:"Wrong default gateway", d:"Host reaches local devices but not remote networks."},
  {t:"Broadcast storm", d:"A switching loop (no STP) flooding broadcasts and saturating the network."},
  {t:"Native VLAN mismatch", d:"Untagged trunk traffic crosses into the wrong VLAN."},
  {t:"Latency / Jitter / Loss", d:"Delay / variation in delay / dropped packets — degrade real-time apps."},
  {t:"Bandwidth saturation", d:"Link near 100% utilization; fix with QoS and/or more capacity."},
  {t:"Co-channel interference", d:"Nearby APs on the same 2.4 GHz channel; fix with 1/6/11."},
  {t:"Attenuation", d:"Signal loss over distance; twisted pair limited to 100 m."},
  {t:"EMI", d:"Electromagnetic interference; mitigate with shielded cabling (STP) or fiber."},
  {t:"Protocol analyzer", d:"Captures and inspects packets (e.g., Wireshark) for deep analysis."},
  {t:"Cable tester", d:"Verifies continuity, wiring order, opens, shorts, and miswires."},
  {t:"Toner and probe", d:"Traces and locates a specific cable among many."},
  {t:"OTDR / optical power meter", d:"Locate faults and measure light levels on fiber runs."},
  {t:"Port scanner (Nmap)", d:"Discovers open ports and services on hosts."},
  {t:"PoE budget exceeded", d:"Too many powered devices; some fail to power on."},
  {t:"Wi-Fi analyzer", d:"Shows channel usage, interference, and signal strength for tuning."}
]
};
