/* ===========================================================
   Security+ SY0-701 — Dedicated Practice Exam Bank
   Fresh, scenario-style questions used ONLY by the full practice exam.
   These do NOT overlap with the per-video quizzes or section exams.
   Keyed by domain (1-5). Each: { q, options[], answer (index), explain }
   =========================================================== */
const EXAM_BANK = {};

/* ---------------- Domain 1: General Security Concepts ---------------- */
Object.assign(EXAM_BANK, { "1": [
  {q:"A security team implements a policy requiring all administrative actions to be logged and tied to a unique user account. Which security goal does this MOST directly support?",
   options:["Confidentiality","Availability","Non-repudiation","Fault tolerance"], answer:2,
   explain:"Tying logged actions to unique identities means a user cannot deny performing them — that is non-repudiation."},
  {q:"An organization cannot replace a legacy application that lacks encryption. Instead, they isolate it on a segmented VLAN with strict ACLs. The VLAN/ACL approach is BEST described as a:",
   options:["Compensating control","Detective control","Corrective control","Directive control"], answer:0,
   explain:"A compensating control is an alternative safeguard used when the primary control (encryption) isn't feasible."},
  {q:"A company posts 'Authorized Personnel Only' signs and installs bright lighting at entrances. These controls primarily function to:",
   options:["Detect intrusions after they occur","Deter potential intruders","Correct a security failure","Encrypt physical assets"], answer:1,
   explain:"Signage and lighting discourage would-be intruders — they are deterrent controls."},
  {q:"Which statement BEST captures the Zero Trust principle of the data plane vs. control plane?",
   options:["The control plane makes policy decisions while the data plane forwards the actual traffic","The data plane decides access and the control plane blocks it","Both planes are merged into one device for speed","Neither plane authenticates requests"], answer:0,
   explain:"In Zero Trust, the control plane (PDP) makes the decision; the data plane (PEP) enforces/forwards traffic accordingly."},
  {q:"A developer needs to confirm a downloaded firmware image is authentic and unmodified. The vendor provides a signature file. To verify it, the developer uses the vendor's:",
   options:["Private key","Public key","Symmetric session key","Password hash"], answer:1,
   explain:"A signature is created with the vendor's private key and verified with their public key."},
  {q:"An auditor reviews an organization's controls against the ISO 27001 framework and lists the differences with a remediation roadmap. This activity is a:",
   options:["Penetration test","Gap analysis","Business impact analysis","Risk transfer"], answer:1,
   explain:"Comparing current state to a target framework and mapping the shortfalls is a gap analysis."},
  {q:"A bank stores a copy of its encryption keys with a trusted third party so encrypted data can be recovered if a key is lost. This practice is called:",
   options:["Key stretching","Key escrow","Perfect forward secrecy","Salting"], answer:1,
   explain:"Key escrow places copies of keys with a trusted party for recovery purposes."},
  {q:"Which scenario BEST demonstrates the use of a honeytoken?",
   options:["A firewall blocking all inbound traffic by default","A fake set of admin credentials that triggers an alert when used","A backup server kept offline","A load balancer distributing traffic"], answer:1,
   explain:"A honeytoken is bait (e.g., fake credentials) whose use signals malicious activity."},
  {q:"An organization wants to allow secure recovery of employee-encrypted files if an employee leaves. Which is the MOST appropriate approach?",
   options:["Disable encryption entirely","Implement key escrow with recovery agents","Share every user's private key with the help desk","Use only symmetric keys printed on paper"], answer:1,
   explain:"Key escrow with authorized recovery agents allows controlled recovery without broadly exposing private keys."},
  {q:"A change request to update a production database is submitted. Per change management, what should be documented BEFORE the change is approved?",
   options:["Only the change's cost","The rollback/backout plan and impact analysis","The employee's home address","Nothing until after deployment"], answer:1,
   explain:"Change management requires an impact analysis and a documented backout plan before approval."},
  {q:"Which of the following provides BOTH integrity and proof of origin for a message?",
   options:["Symmetric encryption alone","A digital signature","A salted password","A VLAN"], answer:1,
   explain:"A digital signature verifies the data wasn't altered (integrity) and confirms who signed it (origin)."},
  {q:"A hospital labels records as 'Restricted' and enforces that only the operating system (not users) can change these labels. This is an example of:",
   options:["Discretionary access control","Mandatory access control","Role-based access control","Rule-based routing"], answer:1,
   explain:"System-enforced labels that users cannot alter describe Mandatory Access Control (MAC)."},
  {q:"Which technology stores cryptographic keys in dedicated hardware and is typically used to protect keys for an entire enterprise at high volume?",
   options:["TPM","HSM","USB flash drive","BIOS"], answer:1,
   explain:"An HSM is a dedicated appliance for enterprise-scale secure key generation and storage; a TPM secures a single device."},
  {q:"A user hides a confidential spreadsheet's data inside an ordinary-looking image file before emailing it. This is:",
   options:["Steganography","Hashing","Tokenization","Load balancing"], answer:0,
   explain:"Concealing data within another file so its existence is hidden is steganography."},
  {q:"A retailer replaces stored credit card numbers with randomly generated values, keeping the real numbers in a separate secured vault. This is:",
   options:["Encryption","Tokenization","Masking","Obfuscation by compression"], answer:1,
   explain:"Tokenization substitutes sensitive data with non-sensitive tokens, with the real data held in a secure vault."},
  {q:"A messaging app generates a new unique session key for each conversation so that compromise of one key does not expose previous chats. This property is:",
   options:["Key escrow","Perfect forward secrecy","Non-repudiation","Data masking"], answer:1,
   explain:"Ephemeral per-session keys provide perfect forward secrecy."},
  {q:"During onboarding, a new hire is given access ONLY to the systems required for their role, nothing more. This reflects which principle?",
   options:["Separation of duties","Least privilege","Implicit trust","Security through obscurity"], answer:1,
   explain:"Granting only the minimum access needed is the principle of least privilege."},
  {q:"Which control category do security awareness training and an acceptable use policy BEST fit into?",
   options:["Physical","Technical","Managerial","Compensating"], answer:2,
   explain:"Policies and training are administrative/managerial controls."},
  {q:"An attacker who obtains yesterday's TLS session key still cannot decrypt today's traffic because new keys are negotiated each session. This is enabled by:",
   options:["A longer password","Ephemeral key exchange (e.g., ECDHE)","Disabling TLS","A wildcard certificate"], answer:1,
   explain:"Ephemeral Diffie-Hellman key exchange creates fresh keys per session, supporting forward secrecy."},
  {q:"A certificate presented by a website has expired. What is the MOST appropriate user action?",
   options:["Ignore the warning and proceed","Do not trust the site and report it","Disable the browser's certificate checking permanently","Reinstall the operating system"], answer:1,
   explain:"An expired/invalid certificate should not be trusted; proceeding or disabling checks introduces risk."},
  {q:"Which pairing correctly matches a control TYPE with an example?",
   options:["Detective — a SIEM alert on anomalous logins","Preventive — restoring from backup","Corrective — a warning banner","Deterrent — an IPS blocking traffic"], answer:0,
   explain:"A SIEM alert detects activity (detective). Restoring is corrective, banners are deterrent/directive, and inline blocking is preventive."},
  {q:"An organization distributes a shared symmetric key by encrypting it with each recipient's public key before sending. The main advantage is:",
   options:["It eliminates the need for any keys","It securely transports the symmetric key over an untrusted channel","It makes the data impossible to decrypt by anyone","It removes the need for hashing"], answer:1,
   explain:"Wrapping a symmetric key with asymmetric encryption lets it be transmitted securely to the intended recipient."},
  {q:"A blockchain maintains integrity primarily because:",
   options:["It is stored on a single trusted server","Each block includes the cryptographic hash of the previous block","Only administrators can read it","It deletes old transactions"], answer:1,
   explain:"Linking blocks via prior-block hashes makes tampering evident and preserves an immutable chain."},
  {q:"Which is the BEST example of authorization (as opposed to authentication)?",
   options:["A user typing a password to log in","A fingerprint scan at login","A file server granting a logged-in user read access to a specific folder","A certificate proving a server's identity"], answer:2,
   explain:"Authorization determines what an already-authenticated identity may access — here, folder read access."}
]});

/* ---------------- Domain 2: Threats, Vulnerabilities & Mitigations ---------------- */
Object.assign(EXAM_BANK, { "2": [
  {q:"An employee receives a text message claiming to be from their bank, urging them to click a link to 'verify' their account. This attack is:",
   options:["Smishing","Vishing","Whaling","Pharming"], answer:0,
   explain:"Phishing delivered via SMS text message is smishing."},
  {q:"An attacker researches a CFO on social media, then emails a convincing invoice request appearing to come from the CEO. This BEST describes:",
   options:["Business email compromise / whaling","A SYN flood","A rainbow table attack","ARP poisoning"], answer:0,
   explain:"Targeting a high-value executive with a tailored, spoofed request is whaling / business email compromise."},
  {q:"A web form passes user input directly into a database query. An attacker enters ' OR '1'='1 to bypass login. The vulnerability is:",
   options:["Cross-site scripting","SQL injection","Buffer overflow","DNS poisoning"], answer:1,
   explain:"Manipulating a database query through unvalidated input is SQL injection; parameterized queries prevent it."},
  {q:"A penetration tester discovers that a comment field stores <script> tags that then execute in other users' browsers. This is:",
   options:["Stored cross-site scripting","Reflected XSS","SQL injection","Directory traversal"], answer:0,
   explain:"Persisting a malicious script on the server that runs for every visitor is stored (persistent) XSS."},
  {q:"A program copies user input into a fixed-size memory buffer without checking length, allowing an attacker to overwrite the return address. This is a:",
   options:["Race condition","Buffer overflow","Logic bomb","Replay attack"], answer:1,
   explain:"Writing past a buffer's boundary to overwrite memory is a buffer overflow; input validation/bounds checks prevent it."},
  {q:"Two processes access a shared file, and an attacker exploits the tiny window between a permission check and the file's use. This vulnerability class is:",
   options:["TOCTOU race condition","Cross-site request forgery","Session replay","Privilege creep"], answer:0,
   explain:"Time-of-check to time-of-use (TOCTOU) races exploit unsynchronized access to a shared resource."},
  {q:"A vulnerability is actively exploited in the wild, but the vendor has not yet released a patch. This is a:",
   options:["Zero-day","Legacy flaw","False positive","Misconfiguration"], answer:0,
   explain:"An unknown/unpatched flaw being exploited is a zero-day."},
  {q:"An organization's public storage bucket is discovered to be readable by anyone on the internet. This is BEST categorized as a:",
   options:["Supply chain attack","Misconfiguration vulnerability","Zero-day","Cryptographic downgrade"], answer:1,
   explain:"Overly permissive/open storage settings are a misconfiguration vulnerability."},
  {q:"Attackers compromise a software vendor's update server so that customers install a trojanized update. This is a:",
   options:["Supply chain attack","Watering hole attack","On-path attack","Password spray"], answer:0,
   explain:"Injecting malicious code through a trusted vendor/update channel is a supply chain attack."},
  {q:"Users of an industry association's website are infected after the site is compromised specifically because attackers know their targets visit it. This is a:",
   options:["Watering hole attack","Whaling attack","SIM swap","Brute force"], answer:0,
   explain:"Compromising a site the intended victims frequent is a watering hole attack."},
  {q:"An attacker sends spoofed ARP replies so that a victim's traffic is routed through the attacker's machine. This enables a(n):",
   options:["On-path (man-in-the-middle) attack","Denial of service only","Cross-site scripting","SQL injection"], answer:0,
   explain:"ARP poisoning redirects traffic through the attacker, enabling an on-path (MITM) attack."},
  {q:"A malware sample encrypts a company's files and displays a payment demand. The MOST effective way to recover without paying is:",
   options:["Restore from tested offline backups","Reboot the affected systems","Change the admin password","Run a port scan"], answer:0,
   explain:"Reliable, tested offline/immutable backups allow recovery from ransomware without paying."},
  {q:"Which malware characteristic distinguishes a worm from a virus?",
   options:["A worm self-propagates across networks without user interaction","A worm requires a host file to spread","A worm cannot replicate","A worm only affects mobile devices"], answer:0,
   explain:"Worms self-replicate over networks automatically; viruses need a host and user action."},
  {q:"Software that appears to be a legitimate utility but secretly opens a backdoor is a:",
   options:["Trojan","Worm","Rootkit","Ransomware"], answer:0,
   explain:"A trojan masquerades as legitimate software while carrying a malicious payload."},
  {q:"Malware that embeds itself in the kernel to hide processes and maintain persistence is a:",
   options:["Rootkit","Adware","Keylogger","Bloatware"], answer:0,
   explain:"Rootkits operate at a low level (e.g., kernel) to conceal themselves and persist."},
  {q:"A disgruntled admin writes code that will delete records if their account is ever disabled. This is a:",
   options:["Logic bomb","Worm","Trojan","Botnet"], answer:0,
   explain:"Code that triggers on a specific condition/event is a logic bomb."},
  {q:"An attacker captures a valid authentication token and later resends it to gain access. Which control MOST directly prevents this?",
   options:["Nonces / timestamps on tokens","Longer usernames","Disabling logging","A wildcard certificate"], answer:0,
   explain:"One-time values (nonces) and expiring timestamps make replayed tokens invalid."},
  {q:"Thousands of compromised IoT devices simultaneously flood a target website, taking it offline. This is a:",
   options:["DDoS using a botnet","Phishing campaign","SQL injection","Privilege escalation"], answer:0,
   explain:"A coordinated flood from many compromised hosts (a botnet) is a Distributed Denial of Service attack."},
  {q:"An attacker sets up a rogue access point named identically to the corporate Wi-Fi to intercept connections. This is an:",
   options:["Evil twin","Amplification attack","Logic bomb","SQL injection"], answer:0,
   explain:"A rogue AP impersonating a legitimate SSID is an evil twin."},
  {q:"Which attack tries a small number of very common passwords across many different accounts to avoid lockouts?",
   options:["Password spraying","Dictionary attack against one account","Rainbow table","Pass-the-hash"], answer:0,
   explain:"Password spraying uses few passwords across many users to stay under lockout thresholds."},
  {q:"An attacker forces a client and server to negotiate an older, weaker cipher that is easier to break. This is a:",
   options:["Downgrade attack","Birthday attack","Collision attack","Replay attack"], answer:0,
   explain:"Downgrade attacks push the connection to weaker cryptography."},
  {q:"Security staff notice a user account logging in from two countries within five minutes. This 'impossible travel' event is BEST described as a(n):",
   options:["Indicator of compromise","False positive by definition","Normal behavior","Compensating control"], answer:0,
   explain:"Impossible-travel logins are a classic indicator of compromise suggesting credential theft."},
  {q:"To limit an attacker's lateral movement after a breach, an organization divides its network into isolated zones. This mitigation is:",
   options:["Segmentation","Single sign-on","Full-disk encryption","Load balancing"], answer:0,
   explain:"Network segmentation contains breaches and restricts lateral movement."},
  {q:"Which mitigation technique allows ONLY explicitly approved applications to run, blocking everything else by default?",
   options:["Application allow-listing","Deny-listing known malware only","Disabling the firewall","Opening all ports"], answer:0,
   explain:"Allow-listing permits only approved apps, blocking unknown/malicious software by default."},
  {q:"An administrator disables unused services, closes unnecessary ports, and changes default credentials on a new server. This process is:",
   options:["Hardening","Tokenizing","Federating","Load balancing"], answer:0,
   explain:"Reducing attack surface by removing/securing defaults and unneeded features is hardening."},
  {q:"A threat actor motivated primarily by ideology and seeking to make a political statement is a(n):",
   options:["Hacktivist","Organized crime group","Nation-state","Script kiddie"], answer:0,
   explain:"Hacktivists are driven by political/social causes rather than profit."},
  {q:"Employees using an unsanctioned cloud file-sharing app without IT approval introduce risk categorized as:",
   options:["Shadow IT","A honeynet","A compensating control","Zero trust"], answer:0,
   explain:"Unauthorized tools/services used outside IT governance are shadow IT."},
  {q:"An attacker plants a specially crafted USB cable that acts as a keyboard to inject commands when connected. This is a:",
   options:["Malicious hardware / physical attack","Cross-site scripting","DNS poisoning","SQL injection"], answer:0,
   explain:"A weaponized cable that injects keystrokes is a physical/hardware attack vector."},
  {q:"A vulnerability scan reports a critical flaw, but investigation shows the affected component isn't actually installed. This is a:",
   options:["False positive","False negative","Zero-day","True positive"], answer:0,
   explain:"A reported vulnerability that doesn't actually exist is a false positive."},
  {q:"Which of the following BEST reduces the risk of a compromised third-party library entering your software?",
   options:["Vetting dependencies and verifying signatures / using an SBOM","Disabling code signing","Trusting all public packages","Removing all logging"], answer:0,
   explain:"Supply-chain risk is reduced by vetting dependencies, verifying signatures, and tracking a software bill of materials."},
  {q:"An attacker exploits a flaw to move from a standard user account to SYSTEM/root privileges. This is:",
   options:["Privilege escalation","Data masking","Key escrow","Segmentation"], answer:0,
   explain:"Gaining higher rights than granted is privilege escalation."}
]});

/* ---------------- Domain 3: Security Architecture ---------------- */
Object.assign(EXAM_BANK, { "3": [
  {q:"A company runs its application code on a provider's platform without managing the underlying OS or servers, deploying only functions triggered by events. This model is:",
   options:["IaaS","Serverless (FaaS)","On-premises","Colocation"], answer:1,
   explain:"Serverless/FaaS runs event-driven code with the provider managing all underlying infrastructure."},
  {q:"In the cloud shared responsibility model for IaaS, which is the CUSTOMER'S responsibility?",
   options:["Securing the physical data center","Patching the hypervisor","Configuring the guest OS, apps, and data","Maintaining the provider's network hardware"], answer:2,
   explain:"In IaaS the customer secures the OS, applications, data, and configurations; the provider secures the infrastructure."},
  {q:"An organization needs the strongest isolation for a highly sensitive research system with no need for external connectivity. The BEST approach is:",
   options:["An air-gapped network","A public DMZ host","A shared VLAN with the office","A cloud bucket set to public"], answer:0,
   explain:"Air gapping physically isolates the system from untrusted networks, providing maximum isolation."},
  {q:"Separating the network's decision-making (control) from packet forwarding (data) to enable centralized, programmable management describes:",
   options:["Software-defined networking (SDN)","RAID","A jump server","Port mirroring"], answer:0,
   explain:"SDN decouples the control plane from the data plane for centralized, programmable control."},
  {q:"A team packages an app with its dependencies so it runs consistently, sharing the host OS kernel rather than running a full guest OS. This is:",
   options:["Containerization","Full virtualization","Bare-metal only","Air gapping"], answer:0,
   explain:"Containers share the host kernel and are lighter than full VMs."},
  {q:"Which device is a hardened single entry point that administrators must connect through to manage sensitive internal servers?",
   options:["Jump server","Load balancer","Web server","Print server"], answer:0,
   explain:"A jump server (jump box) is the controlled, hardened gateway for administrative access."},
  {q:"An e-commerce site experiences uneven traffic and occasional server failures. Which appliance improves both availability and performance by spreading requests?",
   options:["Load balancer","Proxy cache only","IDS","TPM"], answer:0,
   explain:"A load balancer distributes traffic across servers for availability and performance."},
  {q:"The KEY difference between an IPS and an IDS is that an IPS:",
   options:["Only logs events","Sits inline and can actively block malicious traffic","Cannot detect known attacks","Encrypts traffic at rest"], answer:1,
   explain:"An IPS is inline and can block traffic; an IDS only detects and alerts."},
  {q:"A firewall that tracks the state of active connections to permit legitimate return traffic is a:",
   options:["Stateful firewall","Stateless packet filter only","Air gap","VPN concentrator"], answer:0,
   explain:"Stateful firewalls maintain a connection table to allow appropriate return traffic."},
  {q:"Which control BEST protects a public-facing web application from SQL injection and XSS at the network edge?",
   options:["Web Application Firewall (WAF)","NTP server","RAID 5","UPS"], answer:0,
   explain:"A WAF inspects HTTP/S traffic to block web-specific attacks like SQLi and XSS."},
  {q:"A firm requires that all remote employees' internet traffic route through the corporate network for inspection. Which VPN configuration is needed?",
   options:["Full tunnel","Split tunnel","No tunnel","Site-to-site only"], answer:0,
   explain:"Full tunnel routes ALL client traffic through the VPN so it can be inspected."},
  {q:"Two branch offices must securely exchange traffic over the internet as if on one network. The BEST solution is:",
   options:["A site-to-site VPN","A single shared password emailed to staff","Public FTP","Disabling encryption"], answer:0,
   explain:"A site-to-site VPN securely connects two networks over the internet."},
  {q:"Which protocol suite provides encryption and authentication for IP traffic and is commonly used to build VPNs?",
   options:["IPsec","SMTP","SNMPv1","Telnet"], answer:0,
   explain:"IPsec secures IP traffic at the network layer and underpins many VPNs."},
  {q:"802.1X port-based access control relies on which server to make the authentication decision?",
   options:["RADIUS","DHCP","NTP","DNS"], answer:0,
   explain:"802.1X uses a RADIUS authentication server; the switch acts as the authenticator."},
  {q:"Data being processed in a system's memory (RAM) is in which state, and what protects it?",
   options:["Data in use — secure enclaves / confidential computing","Data at rest — full-disk encryption","Data in transit — TLS","Archived data — tape rotation"], answer:0,
   explain:"Data being actively processed is 'in use'; secure enclaves/confidential computing protect it."},
  {q:"An organization labels data as Public, Internal, and Confidential to ensure controls match sensitivity. This practice is:",
   options:["Data classification","Data masking","Tokenization","Load balancing"], answer:0,
   explain:"Assigning sensitivity labels to guide protection is data classification."},
  {q:"A DLP solution is configured to block emails containing credit card numbers from leaving the company. Its primary purpose is to prevent:",
   options:["Data exfiltration","Power loss","DNS spoofing","Buffer overflows"], answer:0,
   explain:"DLP detects and blocks unauthorized movement of sensitive data out of the organization."},
  {q:"A company wants recovery of a critical service within 2 hours of an outage. This target is the:",
   options:["Recovery Time Objective (RTO)","Recovery Point Objective (RPO)","Mean Time To Failure","Annualized Loss Expectancy"], answer:0,
   explain:"RTO is the maximum acceptable time to restore a function after disruption."},
  {q:"Backups run every 4 hours, so up to 4 hours of data could be lost in a failure. This tolerance is the:",
   options:["Recovery Point Objective (RPO)","Recovery Time Objective (RTO)","MTBF","SLA"], answer:0,
   explain:"RPO is the maximum acceptable data loss measured in time, which drives backup frequency."},
  {q:"An organization maintains a fully equipped alternate facility that can assume operations almost immediately. This is a:",
   options:["Hot site","Cold site","Warm site","Mobile site"], answer:0,
   explain:"A hot site is fully operational and ready to take over quickly; cold sites are just space/power."},
  {q:"Which backup strategy captures only the data changed since the last FULL backup (and grows each day until the next full)?",
   options:["Differential","Incremental","Snapshot only","Mirror only"], answer:0,
   explain:"Differential backups include all changes since the last full backup."},
  {q:"Which power resiliency component provides short-term battery power to allow a graceful shutdown during a brief outage?",
   options:["UPS","Generator","PDU only","Surge strip"], answer:0,
   explain:"A UPS supplies short-term battery power; a generator handles longer outages."},
  {q:"An architecture eliminates single points of failure with redundant components and automatic failover to maintain uptime. This design goal is:",
   options:["High availability","Data masking","Non-repudiation","Steganography"], answer:0,
   explain:"Redundancy plus failover to maintain uptime describes high availability."},
  {q:"Placing internet-facing web servers in a network segment isolated from the internal LAN by firewalls describes a:",
   options:["Screened subnet (DMZ)","Air gap","VPN tunnel","RAID array"], answer:0,
   explain:"A screened subnet (DMZ) isolates public-facing servers from the trusted internal network."},
  {q:"Which RAID benefit is MOST relevant to security's availability goal?",
   options:["Data remains accessible despite a disk failure","Files are automatically encrypted","Passwords are hashed","Traffic is load balanced"], answer:0,
   explain:"RAID (depending on level) keeps data available even when a drive fails."},
  {q:"An organization defines infrastructure using version-controlled configuration files so environments are consistent and repeatable. This is:",
   options:["Infrastructure as Code (IaC)","Shadow IT","Air gapping","Tokenization"], answer:0,
   explain:"IaC provisions infrastructure via machine-readable files, improving consistency and automation."}
]});

/* ---------------- Domain 4: Security Operations ---------------- */
Object.assign(EXAM_BANK, { "4": [
  {q:"An administrator applies a standardized secure configuration to every new server image. This standard configuration is a:",
   options:["Secure baseline","Honeypot","Risk register","Compensating control"], answer:0,
   explain:"A documented standard secure configuration systems should match is a secure baseline."},
  {q:"Over months, several servers no longer match the approved secure configuration due to ad-hoc changes. This condition is:",
   options:["Configuration drift","High availability","Least privilege","Tokenization"], answer:0,
   explain:"Gradual deviation from the baseline is configuration drift."},
  {q:"A company lets employees use personal phones for work but installs software to enforce encryption and enable remote wipe. This management approach uses:",
   options:["MDM in a BYOD model","An air gap","A honeynet","A jump server"], answer:0,
   explain:"Mobile Device Management enforces policy and remote wipe; personal-device use is BYOD."},
  {q:"Which wireless configuration is MOST secure for a modern enterprise?",
   options:["WPA3-Enterprise with 802.1X/RADIUS","WEP with a shared key","Open network","WPA2 with the SSID hidden only"], answer:0,
   explain:"WPA3-Enterprise with 802.1X provides the strongest current wireless security."},
  {q:"A developer runs a tool that analyzes source code for vulnerabilities without executing the program. This is:",
   options:["SAST (static analysis)","DAST (dynamic analysis)","Fuzzing a live server","Penetration testing"], answer:0,
   explain:"Static Application Security Testing analyzes source code without running it."},
  {q:"An organization cannot secure or patch assets it doesn't know about. The FIRST step to address this is:",
   options:["Maintain an accurate asset inventory","Buy more firewalls","Disable logging","Increase Wi-Fi range"], answer:0,
   explain:"An accurate inventory is foundational — you can't protect unknown assets."},
  {q:"A vulnerability scan performed with valid login credentials to inspect configuration and patch levels is a:",
   options:["Credentialed scan","Non-credentialed scan","Passive scan only","Port knock"], answer:0,
   explain:"Credentialed (authenticated) scans see deeper detail and reduce false negatives."},
  {q:"A scanner fails to detect a vulnerability that actually exists on a host. This is a:",
   options:["False negative","False positive","True positive","Benign anomaly"], answer:0,
   explain:"A real vulnerability the scan missed is a false negative — the most dangerous outcome."},
  {q:"When prioritizing which vulnerabilities to fix first, which combination is MOST appropriate?",
   options:["CVSS severity plus exposure and business impact","Alphabetical order of CVE IDs","Vendor logo recognition","Random selection"], answer:0,
   explain:"Prioritization weighs severity (CVSS) together with real exposure and impact to your environment."},
  {q:"A team gathers threat data from publicly available websites, forums, and social media. This source type is:",
   options:["OSINT","Proprietary vendor-only feed","Classified intelligence","A honeytoken"], answer:0,
   explain:"Open-Source Intelligence is gathered from publicly available sources."},
  {q:"In a penetration test where the tester is given no internal information beforehand, the engagement is:",
   options:["Unknown environment (black box)","Known environment (white box)","Partially known (gray box)","Tabletop exercise"], answer:0,
   explain:"No prior knowledge simulates an external attacker — an unknown-environment (black box) test."},
  {q:"A platform aggregates logs from firewalls, servers, and endpoints, then correlates events to raise alerts. This is a:",
   options:["SIEM","VPN","UPS","CDN"], answer:0,
   explain:"A SIEM centralizes log collection, correlation, and alerting."},
  {q:"A tool automatically executes a predefined response playbook (e.g., isolate host, open ticket) when a specific alert fires. This capability is:",
   options:["SOAR","RAID","DNS","NAT"], answer:0,
   explain:"SOAR orchestrates and automates response workflows on top of monitoring."},
  {q:"Which endpoint solution continuously records endpoint behavior and lets analysts investigate and respond to threats?",
   options:["EDR","A basic signature-only antivirus","A UPS","A load balancer"], answer:0,
   explain:"Endpoint Detection and Response provides continuous behavioral monitoring and response."},
  {q:"An organization wants unified detection across endpoints, email, network, and cloud from one platform. This is:",
   options:["XDR","EDR limited to one host","SNMP","A jump server"], answer:0,
   explain:"Extended Detection and Response correlates telemetry across multiple layers."},
  {q:"Which set of email mechanisms helps verify sender authenticity and reduce spoofing?",
   options:["SPF, DKIM, and DMARC","RAID, UPS, and PDU","TLS, SSH, and SFTP only","NAT, PAT, and DHCP"], answer:0,
   explain:"SPF, DKIM, and DMARC authenticate senders and reduce spoofed/phishing email."},
  {q:"An administrator must replace insecure Telnet remote access. The BEST secure alternative is:",
   options:["SSH","FTP","HTTP","SNMPv1"], answer:0,
   explain:"SSH provides encrypted remote access, replacing cleartext Telnet."},
  {q:"Which protocol securely transfers files by running the transfer over an SSH connection?",
   options:["SFTP","FTP","TFTP","HTTP"], answer:0,
   explain:"SFTP runs file transfer over the encrypted SSH channel."},
  {q:"A company deploys web filtering that enforces policy on laptops even when off the corporate network. This BEST describes:",
   options:["An agent-based filter","A network-only proxy","A honeypot","A UPS"], answer:0,
   explain:"An endpoint agent enforces web filtering wherever the device goes."},
  {q:"Which access control model assigns permissions based on a user's job role (e.g., 'Accountant')?",
   options:["RBAC","MAC","DAC","Rule-based NAT"], answer:0,
   explain:"Role-Based Access Control assigns access by role/job function."},
  {q:"An access model evaluates attributes such as user department, device posture, and time of day to decide access. This is:",
   options:["ABAC","MAC","DAC","RBAC"], answer:0,
   explain:"Attribute-Based Access Control decides based on combined attributes."},
  {q:"A user logs in once and gains access to email, HR, and file services without re-entering credentials. This is:",
   options:["Single sign-on (SSO)","Multifactor authentication","Least privilege","Air gapping"], answer:0,
   explain:"SSO authenticates once for access to multiple connected systems."},
  {q:"A login requires a password AND a code from a hardware token. This satisfies MFA because it combines:",
   options:["Something you know and something you have","Two things you know","Two passwords","Two biometrics"], answer:0,
   explain:"MFA requires factors from different categories — knowledge (password) and possession (token)."},
  {q:"Which is the CORRECT order of incident response phases?",
   options:["Preparation → Detection/Analysis → Containment → Eradication → Recovery → Lessons Learned","Containment → Preparation → Recovery → Detection","Recovery → Lessons Learned → Preparation → Detection","Detection → Recovery → Preparation → Containment"], answer:0,
   explain:"This is the standard NIST incident response lifecycle."},
  {q:"During a breach investigation, responders must FIRST collect which type of evidence per order of volatility?",
   options:["Contents of RAM/cache","Data on backup tapes","Printed documents","Archived cloud data"], answer:0,
   explain:"The most volatile data (memory/cache) is collected first before it is lost."},
  {q:"To ensure digital evidence is admissible, investigators document every transfer and handler. This documentation is the:",
   options:["Chain of custody","Service level agreement","Risk register","Acceptable use policy"], answer:0,
   explain:"Chain of custody tracks evidence handling to preserve integrity and admissibility."},
  {q:"After receiving notice of pending litigation, an organization must suspend normal deletion of relevant data. This requirement is a:",
   options:["Legal hold","Data classification","Backout plan","Gap analysis"], answer:0,
   explain:"A legal hold preserves potentially relevant data for litigation."},
  {q:"Accurate correlation of log events across many systems depends MOST on:",
   options:["Synchronized time via NTP","Longer passwords","Disabling old logs","Higher screen resolution"], answer:0,
   explain:"NTP keeps clocks aligned so events can be correlated by accurate timestamps."},
  {q:"An IR tabletop exercise is valuable because it:",
   options:["Walks the team through a scenario to validate the plan without impacting production","Physically destroys evidence","Encrypts all endpoints","Replaces the firewall"], answer:0,
   explain:"Tabletop exercises test plans and roles via discussion without operational impact."},
  {q:"Which automation risk should teams guard against when scripting security tasks?",
   options:["A flawed or malicious script can cause rapid, widespread damage","Automation makes tasks slower","Scripts can never be misused","Automation removes the need for any testing"], answer:0,
   explain:"Because automation scales, errors/malicious code scale too — scripts must be tested and secured."},
  {q:"A company enforces standardized security settings across many Windows systems centrally. The BEST tool is:",
   options:["Group Policy (GPO)","A UPS","A CDN","A honeynet"], answer:0,
   explain:"Group Policy pushes standardized security/configuration to many Windows systems."},
  {q:"Timely account deprovisioning matters because:",
   options:["Lingering accounts of departed staff are a common attack vector","Accounts should never be disabled","Everyone should keep admin access","It speeds up the CPU"], answer:0,
   explain:"Orphaned accounts left active after departure are frequently exploited."},
  {q:"Which activity BEST represents proactive vulnerability management after scanning?",
   options:["Remediating (patching) prioritized findings and re-scanning to verify","Ignoring all findings","Disabling the scanner","Publishing the findings publicly"], answer:0,
   explain:"Remediation of prioritized issues followed by verification closes the loop."},
  {q:"A security operations center wants to detect threats that have no known signature. Which capability helps MOST?",
   options:["Behavior/anomaly-based detection","Signature-only antivirus","Disabling monitoring","Static passwords"], answer:0,
   explain:"Anomaly/behavior-based detection can flag novel attacks that signatures miss."}
]});

/* ---------------- Domain 5: Program Management & Oversight ---------------- */
Object.assign(EXAM_BANK, { "5": [
  {q:"Which document is a high-level, mandatory statement of management's intent and expectations for security?",
   options:["Policy","Procedure","Guideline","Runbook"], answer:0,
   explain:"A policy is a high-level mandatory directive; procedures give the detailed steps and guidelines are advisory."},
  {q:"A document specifying that all data at rest must be encrypted with AES-256 is BEST classified as a:",
   options:["Standard","Policy","Guideline","Memo"], answer:0,
   explain:"Standards define specific mandatory requirements that implement policy goals."},
  {q:"Who is typically ACCOUNTABLE for classifying a data set and deciding how it must be protected?",
   options:["Data owner","Data custodian","End user","External auditor"], answer:0,
   explain:"The data owner (a management role) is accountable for classification and protection decisions."},
  {q:"Under privacy regulations, the entity that decides WHY and HOW personal data is processed is the:",
   options:["Data controller","Data processor","Data custodian","Data subject"], answer:0,
   explain:"The controller determines the purposes and means of processing personal data."},
  {q:"A cloud vendor that processes personal data strictly on behalf of your company, per your instructions, is the:",
   options:["Data processor","Data controller","Data owner","Regulator"], answer:0,
   explain:"A processor handles data on behalf of, and per the instructions of, the controller."},
  {q:"An organization documents identified risks with owners, scores, and treatment status in a central location. This is a:",
   options:["Risk register","Incident report","Chain of custody","Baseline"], answer:0,
   explain:"A risk register tracks risks, owners, ratings, and mitigation status."},
  {q:"The amount of risk an organization is willing to accept in pursuit of its objectives is its:",
   options:["Risk appetite","Residual control","Attack surface","Recovery point"], answer:0,
   explain:"Risk appetite is the level of risk leadership is willing to tolerate."},
  {q:"Which analysis assigns monetary values using SLE × ARO to estimate expected yearly loss?",
   options:["Quantitative risk analysis (ALE)","Qualitative risk analysis","Gap analysis","Root cause analysis"], answer:0,
   explain:"Quantitative analysis uses numeric values: ALE = SLE × ARO."},
  {q:"A single fire is expected to cause $200,000 in damage and occurs about once every 10 years. The ALE is:",
   options:["$20,000","$200,000","$2,000,000","$2,000"], answer:0,
   explain:"ALE = SLE ($200,000) × ARO (0.1) = $20,000 per year."},
  {q:"Purchasing cyber-insurance to offset the financial impact of a potential breach is which risk strategy?",
   options:["Transference","Avoidance","Acceptance","Mitigation"], answer:0,
   explain:"Transferring the financial impact to a third party (insurer) is risk transference."},
  {q:"Choosing not to launch a risky new feature at all is which risk strategy?",
   options:["Avoidance","Acceptance","Transference","Mitigation"], answer:0,
   explain:"Eliminating the risk by not undertaking the activity is avoidance."},
  {q:"A study identifies which business functions are most critical and the impact if they are disrupted, defining RTO and RPO. This is a:",
   options:["Business impact analysis (BIA)","Penetration test","Gap analysis","Tabletop exercise"], answer:0,
   explain:"A BIA identifies critical functions and disruption impacts, informing RTO/RPO."},
  {q:"Which metric expresses the average time to restore a failed component to service?",
   options:["MTTR (Mean Time To Repair)","MTBF (Mean Time Between Failures)","RPO","SLE"], answer:0,
   explain:"MTTR measures average repair/restore time; MTBF measures reliability between failures."},
  {q:"Before signing on a new SaaS vendor, a company reviews the vendor's security certifications and audit reports. This is:",
   options:["Vendor due diligence","A honeynet deployment","A downgrade attack","Data masking"], answer:0,
   explain:"Assessing a third party's security posture before engagement is due diligence."},
  {q:"Which agreement defines measurable service expectations such as 99.9% uptime and response times?",
   options:["SLA","NDA","MOU","SOW"], answer:0,
   explain:"A Service Level Agreement specifies measurable service levels and responsibilities."},
  {q:"Two organizations sign a document expressing their mutual intent to collaborate, without strict legal enforceability. This is a:",
   options:["MOU (Memorandum of Understanding)","SLA","NDA","BPA"], answer:0,
   explain:"An MOU expresses intent and is typically less binding than a formal contract."},
  {q:"Which agreement legally binds parties to protect confidential information they share?",
   options:["NDA","SLA","SOW","MSA"], answer:0,
   explain:"A Non-Disclosure Agreement obligates parties to keep shared information confidential."},
  {q:"A document that details the specific deliverables, timeline, and scope of a particular project is a:",
   options:["SOW (Statement of Work)","NDA","MOU","AUP"], answer:0,
   explain:"A Statement of Work specifies the concrete deliverables and scope of work."},
  {q:"Failing to meet regulatory requirements can lead to which consequences?",
   options:["Fines, sanctions, and reputational damage","Automatically stronger security","Free certifications","Guaranteed uptime"], answer:0,
   explain:"Non-compliance carries legal, financial, and reputational consequences."},
  {q:"A regulation that grants individuals the right to request deletion of their personal data is associated with:",
   options:["GDPR (right to be forgotten)","RAID","NTP","802.1X"], answer:0,
   explain:"GDPR includes the right to erasure ('right to be forgotten')."},
  {q:"Data stored in a particular country becomes subject to that country's laws. This concept is:",
   options:["Data sovereignty","Data masking","Tokenization","Key escrow"], answer:0,
   explain:"Data sovereignty means data is governed by the laws of the jurisdiction where it resides."},
  {q:"An assessment performed by an independent third party, adding objectivity and credibility, is a(n):",
   options:["External audit","Internal self-assessment","Tabletop exercise","Gap analysis by staff"], answer:0,
   explain:"External audits are conducted by independent third parties for objectivity."},
  {q:"A formal statement confirming that specific controls are in place and operating is called:",
   options:["Attestation","Repudiation","Sanitization","Provisioning"], answer:0,
   explain:"Attestation is a formal affirmation regarding the state of controls/compliance."},
  {q:"A company runs a controlled fake phishing campaign against employees to measure click rates. The PRIMARY goal is to:",
   options:["Measure and improve user awareness","Actually steal credentials","Punish employees","Bypass the firewall"], answer:0,
   explain:"Phishing simulations safely test and reinforce user awareness, tracked via metrics."},
  {q:"Which practice BEST reduces human-based risk over time?",
   options:["Recurring, role-based security awareness training","A single onboarding video, never repeated","Removing all training to save time","Sharing passwords among the team"], answer:0,
   explain:"Ongoing, role-tailored training keeps security top-of-mind and reduces human risk."},
  {q:"An organization measures the success of its security awareness program primarily by:",
   options:["Reduced phishing click rates and increased reporting","Number of slides in the deck","Length of the training video","Office attendance"], answer:0,
   explain:"Behavioral metrics (click/reporting rates, incident trends) show whether training works."}
]});

