/* ===========================================================
   Security+ SY0-701 — Flashcard decks (Quizlet-style)
   FLASHCARDS keyed by section number. Each card: { t: term, d: definition }
   =========================================================== */
const FLASHCARDS = {
"1": [
  {t:"Confidentiality", d:"Preventing unauthorized disclosure of information. Achieved with encryption, access controls, and data classification."},
  {t:"Integrity", d:"Ensuring data has not been altered. Verified with hashing and digital signatures."},
  {t:"Availability", d:"Ensuring systems and data are accessible when needed. Supported by redundancy, fault tolerance, and backups."},
  {t:"Non-repudiation", d:"Proof that a party performed an action and cannot deny it. Provided by digital signatures."},
  {t:"AAA", d:"Authentication, Authorization, and Accounting — verify identity, grant access rights, and log activity."},
  {t:"Authentication", d:"Proving you are who you claim to be (password, token, biometric, certificate)."},
  {t:"Authorization", d:"Determining what an authenticated identity is allowed to access or do."},
  {t:"Accounting", d:"Recording/auditing the actions a user performs after access is granted."},
  {t:"Zero Trust", d:"'Never trust, always verify.' Every request is authenticated and authorized regardless of location."},
  {t:"Policy Decision Point (PDP)", d:"In Zero Trust, the component that evaluates policy and makes the access decision."},
  {t:"Policy Enforcement Point (PEP)", d:"In Zero Trust, the component that enforces/carries out the access decision."},
  {t:"Control categories", d:"Technical (tech-based), Managerial (policies/procedures), Operational (people-run), Physical (real-world barriers)."},
  {t:"Control types", d:"Preventive, Deterrent, Detective, Corrective, Compensating, and Directive — based on when/how they act."},
  {t:"Compensating control", d:"An alternative control used when the primary control isn't feasible."},
  {t:"Gap analysis", d:"Comparing current security posture to a desired standard/framework to identify shortfalls."},
  {t:"Honeypot", d:"A decoy system designed to attract and study attackers."},
  {t:"Honeynet", d:"A network of honeypots that mimics a realistic environment."},
  {t:"Honeytoken", d:"Fake data (e.g., credentials/records) that triggers an alert if accessed."},
  {t:"Change management", d:"A formal, approved, documented process for making changes to reduce risk and outages."},
  {t:"Symmetric encryption", d:"Uses the SAME secret key to encrypt and decrypt. Fast, but key distribution is the challenge (e.g., AES)."},
  {t:"Asymmetric encryption", d:"Uses a key pair: public key encrypts, matching private key decrypts (e.g., RSA, ECC)."},
  {t:"PKI", d:"Public Key Infrastructure — framework of CAs, certificates, and keys to manage trust."},
  {t:"Certificate Authority (CA)", d:"Trusted entity that issues and digitally signs certificates to vouch for identities."},
  {t:"OCSP / CRL", d:"OCSP checks one certificate's revocation status in real time; a CRL is a downloadable list of revoked certs."},
  {t:"Hashing", d:"A one-way function producing a fixed-length digest to verify integrity (e.g., SHA-256). Not reversible."},
  {t:"Salt", d:"Random data added to a password before hashing to defeat rainbow tables and make hashes unique."},
  {t:"Digital signature", d:"Data signed with the sender's private key — provides integrity, authentication, and non-repudiation."},
  {t:"TPM", d:"Trusted Platform Module — hardware chip on a device for secure key storage and crypto."},
  {t:"HSM", d:"Hardware Security Module — dedicated device for secure key generation/storage at enterprise scale."},
  {t:"Steganography", d:"Hiding data inside other data (e.g., a message concealed in an image)."},
  {t:"Tokenization", d:"Replacing sensitive data with a non-sensitive token; the real data stays in a secure vault."},
  {t:"Perfect forward secrecy", d:"Uses ephemeral session keys so a compromised long-term key can't decrypt past sessions."}
],
"2": [
  {t:"Nation-state / APT", d:"Highly sophisticated, well-funded attacker (often government-backed) focused on espionage/persistence."},
  {t:"Script kiddie", d:"Low-skill attacker using prebuilt tools/scripts created by others."},
  {t:"Hacktivist", d:"Attacker motivated by a political or social cause rather than money."},
  {t:"Insider threat", d:"A current/former employee or partner who misuses authorized access."},
  {t:"Shadow IT", d:"Unauthorized hardware/software/services used without IT approval, expanding risk."},
  {t:"Threat vector", d:"The method or pathway an attacker uses to gain access (email, USB, web, etc.)."},
  {t:"Attack surface", d:"The sum of all points where an attacker could try to enter or extract data."},
  {t:"Phishing", d:"Fraudulent messages tricking users into revealing data or clicking malicious links."},
  {t:"Spear phishing", d:"Phishing targeted at a specific individual/organization with tailored content."},
  {t:"Whaling", d:"Phishing aimed at high-profile executives (the 'big fish')."},
  {t:"Vishing / Smishing", d:"Phishing via voice calls (vishing) or SMS text messages (smishing)."},
  {t:"Pretexting / Impersonation", d:"Using a fabricated identity or scenario to manipulate a victim into acting."},
  {t:"Watering hole attack", d:"Compromising a trusted website the target group frequents, then waiting for them to visit."},
  {t:"Typosquatting", d:"Registering misspelled domains to catch users who mistype a URL."},
  {t:"Buffer overflow", d:"Writing more data to a buffer than it holds, overwriting memory to crash or run code."},
  {t:"Race condition (TOCTOU)", d:"Exploiting the timing gap between time-of-check and time-of-use of a resource."},
  {t:"SQL injection", d:"Injecting malicious SQL via input to read/modify a database. Stopped by parameterized queries."},
  {t:"Cross-site scripting (XSS)", d:"Injecting scripts that run in other users' browsers to steal data/sessions."},
  {t:"Privilege escalation", d:"Gaining higher access rights than intended (e.g., user → admin)."},
  {t:"Zero-day", d:"A vulnerability unknown to the vendor with no patch available yet."},
  {t:"Virus vs Worm", d:"A virus needs a host file and user action; a worm self-replicates across networks automatically."},
  {t:"Ransomware", d:"Malware that encrypts data and demands payment. Best recovery: offline/immutable backups."},
  {t:"Rootkit", d:"Malware that hides deep in the system (kernel/boot) to evade detection and persist."},
  {t:"Logic bomb", d:"Malicious code that triggers when a specific condition or time is met."},
  {t:"Trojan", d:"Malware disguised as legitimate software to trick users into running it."},
  {t:"Botnet", d:"A network of compromised devices controlled by an attacker (used for DDoS, spam, etc.)."},
  {t:"DDoS", d:"Distributed Denial of Service — many systems overwhelm a target to harm availability."},
  {t:"DNS poisoning", d:"Corrupting DNS resolution so a trusted name resolves to a malicious IP. DNSSEC helps defend."},
  {t:"On-path (MITM)", d:"Attacker intercepts/alters traffic between two parties. Defended by TLS with cert validation."},
  {t:"Replay attack", d:"Capturing valid data (e.g., a token) and resending it. Prevented by nonces/timestamps."},
  {t:"Password spraying", d:"Trying one common password across many accounts to avoid lockouts."},
  {t:"Indicator of Compromise (IoC)", d:"Evidence suggesting a breach (odd traffic, impossible-travel logins, account lockouts)."}
],
"3": [
  {t:"IaaS / PaaS / SaaS", d:"Cloud models: Infrastructure, Platform, or Software as a Service — provider manages progressively more."},
  {t:"Serverless (FaaS)", d:"Provider runs your code/functions on demand; no servers for you to manage."},
  {t:"SDN", d:"Software-Defined Networking — separates the control plane (decisions) from the data plane (forwarding)."},
  {t:"Containerization", d:"Packaging apps with dependencies; containers share the host OS kernel (lighter than full VMs)."},
  {t:"Infrastructure as Code (IaC)", d:"Provisioning infrastructure via machine-readable config files for consistency and automation."},
  {t:"Air gap", d:"Physical isolation of a system/network from untrusted networks for security."},
  {t:"VLAN", d:"Logically segments a switch into isolated broadcast domains without separate hardware."},
  {t:"Screened subnet (DMZ)", d:"A buffer zone hosting public-facing servers, separated from the internal network."},
  {t:"IDS vs IPS", d:"IDS detects and alerts only; IPS sits inline and can actively block malicious traffic."},
  {t:"Jump server", d:"A hardened, controlled gateway admins use to access sensitive internal systems."},
  {t:"Load balancer", d:"Distributes traffic across multiple servers for availability and performance."},
  {t:"Proxy server", d:"Intermediary between clients and servers enabling filtering, caching, and monitoring."},
  {t:"802.1X", d:"Port-based network access control requiring authentication (via RADIUS) before network access."},
  {t:"NGFW", d:"Next-Generation Firewall — adds application awareness, deep packet inspection, and IPS."},
  {t:"Stateful firewall", d:"Tracks the state of active connections to allow legitimate return traffic."},
  {t:"WAF", d:"Web Application Firewall — inspects HTTP/S to block web attacks like SQLi and XSS."},
  {t:"Site-to-site VPN", d:"Securely connects two whole networks (e.g., offices) over the internet."},
  {t:"IPsec", d:"Encrypts and authenticates IP traffic at the network layer; common for VPNs."},
  {t:"Full vs split tunnel", d:"Full tunnel routes ALL client traffic through the VPN; split tunnel only some."},
  {t:"States of data", d:"At rest (stored), in transit (moving), in use (being processed). Each needs different protection."},
  {t:"Data classification", d:"Labeling data (public/confidential/restricted) so controls match sensitivity."},
  {t:"PII / PHI", d:"Personally Identifiable Information / Protected Health Information — sensitive, often regulated."},
  {t:"DLP", d:"Data Loss Prevention — detects and blocks unauthorized exfiltration of sensitive data."},
  {t:"RAID", d:"Combines disks for redundancy and/or performance so data survives a drive failure."},
  {t:"Hot / Warm / Cold site", d:"DR sites: hot is fully ready, warm is partially equipped, cold is just space/power."},
  {t:"RTO vs RPO", d:"RTO = max time to restore a function; RPO = max acceptable data loss (in time)."},
  {t:"Full / Incremental / Differential", d:"Backup types: full = everything; incremental = changes since last backup; differential = changes since last full."},
  {t:"UPS vs Generator", d:"UPS gives short-term battery for brief outages/shutdown; a generator provides longer-term power."},
  {t:"High availability (HA)", d:"Designing for continuous uptime via redundancy and eliminating single points of failure."}
],
"4": [
  {t:"Secure baseline", d:"A documented standard secure configuration that systems should match."},
  {t:"Configuration drift", d:"Systems gradually deviating from the secure baseline over time, reintroducing risk."},
  {t:"MDM", d:"Mobile Device Management — centrally enforce policy, push configs, and remotely wipe devices."},
  {t:"BYOD / COPE / CYOD", d:"Device models: Bring Your Own Device, Corporate-Owned Personally Enabled, Choose Your Own Device."},
  {t:"WPA3", d:"Latest, most secure Wi-Fi standard (uses SAE). WEP/WPA are deprecated."},
  {t:"SAST vs DAST", d:"SAST scans source code statically; DAST tests the running application dynamically."},
  {t:"Asset management", d:"Identifying, tracking, and securing all hardware/software; includes secure disposal/sanitization."},
  {t:"Credentialed scan", d:"A vulnerability scan that logs in for deeper, more accurate results (fewer false negatives)."},
  {t:"False positive vs negative", d:"False positive = reported flaw that isn't real; false negative = a real flaw the scan missed."},
  {t:"CVE", d:"Common Vulnerabilities and Exposures — a unique ID for a publicly known vulnerability."},
  {t:"CVSS", d:"Common Vulnerability Scoring System — rates vulnerability severity from 0–10."},
  {t:"Threat intelligence / OSINT", d:"Information about threats; OSINT is gathered from publicly available sources."},
  {t:"Pen test box types", d:"Black box (no info), white box (full info), gray box (partial info)."},
  {t:"SIEM", d:"Security Information and Event Management — aggregates and correlates logs for alerting/analysis."},
  {t:"SOAR", d:"Security Orchestration, Automation, and Response — automates and coordinates incident response."},
  {t:"EDR vs XDR", d:"EDR continuously monitors endpoints; XDR correlates across endpoints, network, cloud, and more."},
  {t:"SPF / DKIM / DMARC", d:"Email authentication mechanisms that validate senders and reduce spoofing/phishing."},
  {t:"Secure protocols", d:"Use SSH (vs Telnet), SFTP/FTPS (vs FTP), HTTPS (vs HTTP), SNMPv3, etc."},
  {t:"IAM", d:"Identity and Access Management — provisioning, deprovisioning, and governing identities/access."},
  {t:"SSO", d:"Single Sign-On — authenticate once to access multiple connected systems."},
  {t:"Federation", d:"Using a trusted identity provider to authenticate across different organizations/domains."},
  {t:"RBAC", d:"Role-Based Access Control — permissions assigned based on a user's role/job function."},
  {t:"MAC (access control)", d:"Mandatory Access Control — access based on system-enforced labels/classifications, not the owner."},
  {t:"DAC", d:"Discretionary Access Control — the data owner decides who gets access."},
  {t:"ABAC", d:"Attribute-Based Access Control — access decisions based on attributes (user, resource, environment)."},
  {t:"MFA factors", d:"Something you know, have, are, plus somewhere you are / something you do."},
  {t:"Incident response phases", d:"Preparation → Detection/Analysis → Containment → Eradication → Recovery → Lessons Learned."},
  {t:"Chain of custody", d:"Documentation tracking evidence handling to keep it admissible (who/what/when/where)."},
  {t:"Order of volatility", d:"Collect the most volatile evidence first (RAM/cache) before disk and archives."},
  {t:"Legal hold", d:"A requirement to preserve relevant data for potential litigation (suspends normal deletion)."},
  {t:"NTP for logs", d:"Synchronized time across systems so log events can be accurately correlated."}
],
"5": [
  {t:"Policy", d:"High-level, mandatory statement of management's security expectations and goals."},
  {t:"Standard", d:"Specific, mandatory requirements that support a policy (e.g., required encryption)."},
  {t:"Procedure", d:"Detailed step-by-step instructions to accomplish a task consistently."},
  {t:"Guideline", d:"Recommended, non-mandatory best-practice advice."},
  {t:"AUP", d:"Acceptable Use Policy — defines how employees may use organizational systems/resources."},
  {t:"Data owner", d:"Senior/management role accountable for data, including its classification and protection."},
  {t:"Data custodian/steward", d:"Handles day-to-day technical protection/storage of data as directed by the owner."},
  {t:"Data controller", d:"Entity that determines the purposes and means of processing personal data."},
  {t:"Data processor", d:"Entity that processes personal data on behalf of the controller."},
  {t:"Risk", d:"A function of likelihood (threat exploiting a vulnerability) and impact."},
  {t:"Risk register", d:"A document tracking identified risks, owners, scores, and treatment status."},
  {t:"Risk appetite/tolerance", d:"The amount of risk an organization is willing to accept to meet its objectives."},
  {t:"Qualitative vs quantitative", d:"Qualitative rates risk subjectively (high/med/low); quantitative uses numbers/money (SLE, ARO, ALE)."},
  {t:"SLE / ARO / ALE", d:"Single Loss Expectancy × Annual Rate of Occurrence = Annualized Loss Expectancy."},
  {t:"Risk strategies", d:"Accept, Avoid, Transfer (e.g., insurance), or Mitigate (apply controls)."},
  {t:"BIA", d:"Business Impact Analysis — identifies critical functions and impacts of disruption (defines RTO/RPO)."},
  {t:"MTBF / MTTR", d:"Mean Time Between Failures (reliability) / Mean Time To Repair (recovery speed)."},
  {t:"Third-party / supply chain risk", d:"Risk introduced by vendors, suppliers, and service providers in your chain."},
  {t:"Due diligence", d:"Evaluating a third party's security posture before and during an engagement."},
  {t:"SLA", d:"Service Level Agreement — defines expected service levels, metrics, and responsibilities."},
  {t:"MOU / MSA / SOW", d:"MOU = intent (less binding); MSA = master terms; SOW = specific work/deliverables."},
  {t:"NDA", d:"Non-Disclosure Agreement — legally binds parties to protect confidential information."},
  {t:"Compliance", d:"Adhering to laws/regulations/standards; non-compliance brings fines and reputational damage."},
  {t:"GDPR", d:"EU privacy regulation governing personal data; grants rights like the 'right to be forgotten.'"},
  {t:"Data sovereignty", d:"Data is subject to the laws of the country where it is physically stored."},
  {t:"Internal vs external audit", d:"External audits add independence/objectivity; internal audits are done by the organization itself."},
  {t:"Attestation", d:"A formal statement/confirmation that controls or compliance requirements are met."},
  {t:"Penetration test", d:"Actively exploits vulnerabilities to demonstrate real-world risk (beyond just scanning)."},
  {t:"Security awareness training", d:"Educating users to recognize and avoid threats; reduces human risk."},
  {t:"Phishing simulation", d:"A controlled fake phishing campaign to measure and improve user awareness."}
]
};
